package k8s

import (
	"fmt"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/structured-merge-diff/v6/fieldpath"

	"github.com/podsteer/podsteer/app/domain"
)

// FieldOwnership decodes an object's metadata.managedFields into something a
// human can read. See ports.ManagementPort.FieldOwnership.
//
// A METHOD WITH NOTHING TO DO WITH THE ADAPTER'S STATE, because the port is
// where the frontend reaches it and the port is this interface. The work is
// in decodeFieldOwnership, which is a function because that is what it is.
func (a *Adapter) FieldOwnership(manifest string) (domain.FieldOwnership, error) {
	return decodeFieldOwnership(manifest)
}

// decodeFieldOwnership is the transform itself.
//
// NO CLUSTER CALL, AND THAT IS THE POINT. The manifest is already in hand —
// the drawer fetched it for the YAML tab — so this is a pure transform of
// bytes the operator is already looking at. It takes no ClusterID and no
// context because it talks to nothing.
//
// THE PATHS ARE NOT IMITATED, THEY ARE GENERATED BY THE SAME LIBRARY. The
// API server builds `.spec.template.spec.containers[name="web"].image` with
// structured-merge-diff's fieldpath.Path.String, and so does this, so the
// ownership panel and a conflict dialog are guaranteed to spell the same
// field the same way rather than agreeing by inspection today and drifting
// tomorrow. Hand-rolling the `f:`/`k:` walk was the alternative and would
// have meant maintaining a private copy of somebody else's serialization
// format.
//
// ENTRIES ARE KEPT SEPARATE BY OPERATION. `podsteer`/Update and
// `podsteer`/Apply are two rows here because they are two rows on the server
// — see domain.FieldOwner.Operation, and ApplyResource for what that split
// costs when it is hidden.
func decodeFieldOwnership(manifest string) (domain.FieldOwnership, error) {
	obj, err := decodeManifest(manifest)
	if err != nil {
		// decodeManifest's errors are already scrubbed of manifest content —
		// see its own comment on why the library's message never surfaces.
		return nil, err
	}

	entries := obj.GetManagedFields()
	ownership := make(domain.FieldOwnership, 0, len(entries))
	for _, entry := range entries {
		owner, err := decodeManagedFieldsEntry(entry)
		if err != nil {
			return nil, err
		}
		ownership = append(ownership, owner)
	}
	return ownership, nil
}

// decodeManagedFieldsEntry turns one server entry into one owner.
func decodeManagedFieldsEntry(entry metav1.ManagedFieldsEntry) (domain.FieldOwner, error) {
	owner := domain.FieldOwner{
		Manager:     entry.Manager,
		Kind:        domain.ClassifyManager(entry.Manager),
		Operation:   string(entry.Operation),
		Subresource: entry.Subresource,
	}
	if entry.Time != nil {
		owner.UpdatedAt = entry.Time.UTC().Format(time.RFC3339)
	}

	// An entry with no fieldsV1 is not an error: the server writes one for a
	// manager whose whole contribution was removed, and for entries in the
	// older fieldsV1beta1 shape this does not read. An owner with no fields
	// renders as exactly that.
	if entry.FieldsV1 == nil || entry.FieldsV1.GetRawBytes() == nil {
		return owner, nil
	}

	set := &fieldpath.Set{}
	if err := set.FromJSON(entry.FieldsV1.GetRawReader()); err != nil {
		// The manager's NAME is safe to name — it is not an object name and
		// it is already on screen. The fieldsV1 blob is not repeated: its
		// keys are field paths of an object that may be a Secret, and a
		// Secret's KEY NAMES are as much of a disclosure as this codebase
		// allows itself to avoid.
		return domain.FieldOwner{}, fmt.Errorf("reading the ownership record written by %q: %w",
			entry.Manager, err)
	}

	// Iterate rather than Leaves: a manager that owns `.metadata.labels`
	// whole AND one label inside it holds both facts, and Leaves would drop
	// the first. Preorder DFS over a sorted structure, so the paths come out
	// sorted without sorting them.
	set.Iterate(func(path fieldpath.Path) {
		owner.Fields = append(owner.Fields, path.String())
	})

	return owner, nil
}
