// Code generated by tools/releasegen. DO NOT EDIT.
//
// Source, both maintained by the Kubernetes release team:
//   https://raw.githubusercontent.com/kubernetes/website/main/data/releases/schedule.yaml
//   https://raw.githubusercontent.com/kubernetes/website/main/data/releases/eol.yaml
//
// Regenerate with: make releases

package domain

import "time"

// scheduleCompiledAt is when this table was generated.
//
// Carried so the application can say how old its answer is rather than
// implying it is current. A build from a year ago knows nothing about releases
// made since it, and the difference between "not in the table" and "does not
// exist" is the whole reason an unknown version is reported as unknown.
var scheduleCompiledAt = time.Date(2026, 8, 23, 0, 0, 0, 0, time.UTC)

// endOfLife maps a Kubernetes minor version to the day its patches stop.
var endOfLife = map[string]time.Time{
	"1.36": time.Date(2027, 6, 28, 0, 0, 0, 0, time.UTC),
	"1.35": time.Date(2027, 2, 28, 0, 0, 0, 0, time.UTC),
	"1.34": time.Date(2026, 10, 27, 0, 0, 0, 0, time.UTC),
	"1.33": time.Date(2026, 6, 28, 0, 0, 0, 0, time.UTC),
	"1.32": time.Date(2026, 2, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.32.13
	"1.31": time.Date(2025, 11, 11, 0, 0, 0, 0, time.UTC), // final patch 1.31.14
	"1.30": time.Date(2025, 7, 15, 0, 0, 0, 0, time.UTC),  // final patch 1.30.14
	"1.29": time.Date(2025, 2, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.29.14
	"1.28": time.Date(2024, 10, 22, 0, 0, 0, 0, time.UTC), // final patch 1.28.15
	"1.27": time.Date(2024, 7, 16, 0, 0, 0, 0, time.UTC),  // final patch 1.27.16
	"1.26": time.Date(2024, 2, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.26.15
	"1.25": time.Date(2023, 10, 28, 0, 0, 0, 0, time.UTC), // final patch 1.25.16
	"1.24": time.Date(2023, 7, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.24.17
	"1.23": time.Date(2023, 2, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.23.17
	"1.22": time.Date(2022, 12, 8, 0, 0, 0, 0, time.UTC),  // final patch 1.22.17
	"1.21": time.Date(2022, 6, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.21.14
	"1.20": time.Date(2022, 2, 28, 0, 0, 0, 0, time.UTC),  // final patch 1.20.15
	"1.19": time.Date(2021, 10, 28, 0, 0, 0, 0, time.UTC), // final patch 1.19.16
	"1.18": time.Date(2021, 6, 18, 0, 0, 0, 0, time.UTC),  // final patch 1.18.20
	"1.17": time.Date(2021, 1, 13, 0, 0, 0, 0, time.UTC),  // final patch 1.17.17
	"1.16": time.Date(2020, 9, 2, 0, 0, 0, 0, time.UTC),   // final patch 1.16.15
	"1.15": time.Date(2020, 5, 6, 0, 0, 0, 0, time.UTC),   // final patch 1.15.12
	"1.14": time.Date(2019, 12, 11, 0, 0, 0, 0, time.UTC), // final patch 1.14.10
	"1.13": time.Date(2019, 10, 15, 0, 0, 0, 0, time.UTC), // final patch 1.13.12
	"1.12": time.Date(2019, 7, 8, 0, 0, 0, 0, time.UTC),   // final patch 1.12.10
	"1.11": time.Date(2019, 5, 1, 0, 0, 0, 0, time.UTC),   // final patch 1.11.10
	"1.10": time.Date(2019, 2, 13, 0, 0, 0, 0, time.UTC),  // final patch 1.10.13
	"1.9":  time.Date(2018, 9, 29, 0, 0, 0, 0, time.UTC),  // final patch 1.9.11
	"1.8":  time.Date(2018, 7, 12, 0, 0, 0, 0, time.UTC),  // final patch 1.8.15
	"1.7":  time.Date(2018, 4, 4, 0, 0, 0, 0, time.UTC),   // final patch 1.7.16
	"1.6":  time.Date(2017, 11, 23, 0, 0, 0, 0, time.UTC), // final patch 1.6.13
	"1.5":  time.Date(2017, 10, 1, 0, 0, 0, 0, time.UTC),  // final patch 1.5.8
	"1.4":  time.Date(2017, 4, 21, 0, 0, 0, 0, time.UTC),  // final patch 1.4.12
	"1.3":  time.Date(2016, 11, 1, 0, 0, 0, 0, time.UTC),  // final patch 1.3.10
	"1.2":  time.Date(2016, 10, 23, 0, 0, 0, 0, time.UTC), // final patch 1.2.7
}
