package notices_test

import (
	"strings"
	"testing"

	"github.com/podsteer/podsteer/app/adapters/notices"
)

// These tests assert properties of the COMMITTED inventory, not of the code
// that reads it. That is deliberate: the inventory is generated by a Node
// script that CI runs, but the obligation it discharges is carried by the Go
// binary — so the Go build is the last place the claim can be checked before
// something ships. A `go test ./...` on a machine with no Node still catches a
// hand-edited or truncated notices.json.

// forbidden are the licences that must never appear in a shipped dependency.
// Duplicated from build/licence-policy.json on purpose: two independent
// statements of the same rule, so editing the policy file alone cannot make a
// forbidden licence pass.
var forbidden = []string{"GPL-2.0", "GPL-3.0", "AGPL-3.0", "SSPL-1.0", "BUSL-1.1", "Elastic-2.0"}

func TestPackagesLoad(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}
	// A plausible floor. The point is to catch a truncated or emptied file,
	// which would otherwise satisfy every other assertion here vacuously.
	if len(packages) < 50 {
		t.Fatalf("packages = %d, want the full inventory — is notices.json truncated?", len(packages))
	}
}

func TestEveryPackageIsIdentified(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	for _, entry := range packages {
		if strings.TrimSpace(entry.Name) == "" {
			t.Error("a package has no name")
		}
		if strings.TrimSpace(entry.Licence) == "" {
			t.Errorf("%s has no licence", entry.Name)
		}
		if entry.Ecosystem != "go" && entry.Ecosystem != "npm" {
			t.Errorf("%s has an unexpected ecosystem %q", entry.Name, entry.Ecosystem)
		}
	}
}

// The defence-in-depth check: whatever the policy file says, the binary must
// not be built against a copyleft dependency.
func TestNoForbiddenLicenceShips(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	for _, entry := range packages {
		for _, banned := range forbidden {
			if strings.EqualFold(entry.Licence, banned) {
				t.Errorf("%s:%s ships under %s, which the licence policy forbids",
					entry.Ecosystem, entry.Name, entry.Licence)
			}
		}
	}
}

// Nothing may claim "UNKNOWN" in the shipped set: an unclassified licence is
// exactly what the policy routes to human review, so one reaching the binary
// means the review was skipped.
func TestNoShippedPackageIsUnclassified(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	for _, entry := range packages {
		if entry.Licence == "UNKNOWN" {
			t.Errorf("%s:%s has an unclassified licence", entry.Ecosystem, entry.Name)
		}
	}
}

// Every text id a package points at must resolve, or the Credits pane offers
// a licence it cannot show.
func TestEveryReferencedTextResolves(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	for _, entry := range packages {
		if entry.TextID != "" {
			if _, ok := notices.Text(entry.TextID); !ok {
				t.Errorf("%s references licence text %q, which is not in the inventory",
					entry.Name, entry.TextID)
			}
		}
		if entry.NoticeTextID != "" {
			if _, ok := notices.Text(entry.NoticeTextID); !ok {
				t.Errorf("%s references NOTICE text %q, which is not in the inventory",
					entry.Name, entry.NoticeTextID)
			}
		}
	}
}

// The three modules only the Windows binary links. They were missing from the
// first version of this inventory because `go list -deps` ran on the host
// platform alone, which is precisely the regression this guards.
func TestWindowsOnlyModulesAreCovered(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	present := make(map[string]bool, len(packages))
	for _, entry := range packages {
		present[entry.Name] = true
	}

	for _, name := range []string{
		"github.com/wailsapp/go-webview2",
		"github.com/Azure/go-ansiterm",
		"github.com/inconshreveable/mousetrap",
	} {
		if !present[name] {
			t.Errorf("%s is linked into the Windows build but is absent from the notices; "+
				"the inventory was generated for one platform only", name)
		}
	}
}

// Unlicensed dependencies are the ones that get a distribution stopped, so
// the count is pinned rather than merely allowed. Raising it is a decision.
func TestPackagesWithoutLicenceTextAreKnown(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	// Both declare MIT in package.json but publish no licence file upstream.
	// Reproducing a notice that does not exist is impossible; recording that
	// is the honest alternative.
	known := map[string]bool{"is-reference": true, "locate-character": true}

	for _, entry := range packages {
		if entry.TextID == "" && !known[entry.Name] {
			t.Errorf("%s:%s ships no licence text and is not a known exception — "+
				"MIT and BSD both require the notice to be distributed",
				entry.Ecosystem, entry.Name)
		}
	}
}

func TestTextsAreShared(t *testing.T) {
	t.Parallel()

	texts, err := notices.Texts()
	if err != nil {
		t.Fatalf("Texts() error = %v", err)
	}
	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	// Deduplication is what keeps the embedded file small; if every package
	// carried its own copy this would be roughly one-to-one.
	if len(texts) >= len(packages) {
		t.Errorf("texts = %d for %d packages, want the identical ones shared",
			len(texts), len(packages))
	}
}

func TestUnknownTextIsReportedMissing(t *testing.T) {
	t.Parallel()

	if _, ok := notices.Text("not-a-real-id"); ok {
		t.Error("an unknown text id must not resolve")
	}
	if _, ok := notices.Text(""); ok {
		t.Error("an empty text id must not resolve")
	}
}

// A notice inherited from a sibling still has to BE there. The mechanism in
// build/licences/notice-sources.json exists so a package that ships no licence
// of its own is still credited with one — MIT requires the notice to be
// distributed, and a tarball omitting the file does not remove that duty.
//
// This asserts the outcome rather than the mechanism: whatever the collector
// did, the inventory that reaches Settings → Credits must carry both the text
// and a record that it was inherited, so the file never implies the package
// shipped something it did not.
func TestInheritedNoticesCarryTextAndProvenance(t *testing.T) {
	t.Parallel()

	packages, err := notices.Packages()
	if err != nil {
		t.Fatalf("Packages() error = %v", err)
	}

	inherited := 0
	for _, entry := range packages {
		if entry.NoticeFrom == "" {
			continue
		}
		inherited++

		if entry.TextID == "" {
			t.Errorf("%s inherits a notice from %s but carries no text",
				entry.Name, entry.NoticeFrom)
		}
		if entry.Copyright == "" {
			t.Errorf("%s inherits a notice from %s but carries no copyright line — "+
				"that is the part MIT and BSD name specifically", entry.Name, entry.NoticeFrom)
		}
	}

	// Not a requirement that any exist, but if the mechanism is wired and
	// silently matching nothing, the entries in notice-sources.json are stale
	// and the packages they cover are shipping uncredited.
	t.Logf("%d package(s) carry an inherited notice", inherited)
}
