// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowseAPI exposes navigation, events and the generic resource browser.
 * 
 * It is the API that makes the navigator work for kinds PodSteer has no
 * purpose-built view for — including every CRD in the cluster.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssessCertificateRenewal says whether a cert-manager Certificate is running
 * out without being renewed.
 * 
 * A PURE CALL, exactly like ClassifyConditions above and there for exactly
 * the same reason: the cert-manager panel quotes the manifest the drawer
 * already holds, and quoting needs no round trip — but status.notAfter and
 * status.renewalTime are DATES, and the question an operator opens a
 * Certificate to ask is a comparison between them, the Ready condition and
 * the clock. A comparison is a verdict; verdicts live in the domain where
 * domain.AssessCertificateRenewal's rules are argued with in a test rather
 * than discovered during an outage.
 * 
 * Returns an empty list for a healthy certificate, which is the answer for
 * almost all of them.
 */
export function AssessCertificateRenewal(certificate: $models.CertificateRenewalRef): $CancellablePromise<$models.CertificateInsight[] | null> {
    return $Call.ByID(3937151102, certificate);
}

/**
 * ClassifyConditions says which of an object's status conditions report a
 * problem.
 * 
 * A PURE CALL — it reaches no cluster and cannot fail. It exists because the
 * polarity of a condition is a verdict and verdicts live in the domain (see
 * CLAUDE.md), and because getting one backwards is invisible until somebody
 * is reading the wrong colour during an incident: the rule it replaced
 * coloured every healthy node as a warning.
 * 
 * Takes the whole list rather than one condition, so a panel showing eight of
 * them crosses the boundary once.
 */
export function ClassifyConditions(conditions: $models.ConditionRef[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(4275292557, conditions);
}

/**
 * GetManifest returns one object as YAML, for the detail view.
 * 
 * revealSecrets applies to core/v1 Secrets and nothing else: false replaces
 * their values with the decoded SIZE, the way `kubectl describe secret` does.
 * The default is false at every call site, and the true path exists only
 * behind a deliberate click — reading a Secret is an audited action, and the
 * YAML tab would otherwise perform one every time somebody browsed past.
 */
export function GetManifest(clusterID: string, kindID: string, $namespace: string, name: string, revealSecrets: boolean): $CancellablePromise<string> {
    return $Call.ByID(2719837910, clusterID, kindID, $namespace, name, revealSecrets);
}

/**
 * InspectTLSSecret parses one Secret's certificate material, for a
 * deliberate inspection.
 * 
 * The same discipline as RevealSecretKey: nothing in PodSteer calls this
 * except a person pressing "Inspect certificate" in the Secret pane, because
 * reading a Secret is audited whichever half of it somebody wanted. The
 * private key itself never crosses this boundary — only whether it matched
 * the certificate, as a bool on the returned chain.
 */
export function InspectTLSSecret(clusterID: string, $namespace: string, name: string): $CancellablePromise<$models.CertificateChainDTO> {
    return $Call.ByID(3910157316, clusterID, $namespace, name);
}

/**
 * ListEvents returns a cluster's events, warnings first and most recent first.
 * 
 * annotationKeys names the annotations each row should carry — the same
 * projection WorkloadAPI.ListPods takes, for the same reason.
 */
export function ListEvents(clusterID: string, $namespace: string, annotationKeys: string[] | null): $CancellablePromise<$models.Event[] | null> {
    return $Call.ByID(1396241276, clusterID, $namespace, annotationKeys);
}

/**
 * ListEventsForResource returns events for a specific resource, warnings first and most recent first.
 */
export function ListEventsForResource(clusterID: string, $namespace: string, kind: string, name: string): $CancellablePromise<$models.Event[] | null> {
    return $Call.ByID(781778495, clusterID, $namespace, kind, name);
}

/**
 * ListKinds returns every browsable kind in a connected cluster.
 * 
 * The navigator tree is built from this rather than hard-coded in the
 * frontend, so a cluster's own operators appear in it without a frontend
 * change.
 */
export function ListKinds(clusterID: string): $CancellablePromise<$models.ResourceKind[] | null> {
    return $Call.ByID(3347351192, clusterID);
}

/**
 * ListTable returns objects of any kind as a table, with the columns the API
 * server prints. This is the generic path behind Config, Network, Storage,
 * Access Control and Custom Resources.
 * 
 * annotationKeys is the same projection ListEvents takes; every row also
 * carries its labels, read from the table's own row metadata.
 */
export function ListTable(clusterID: string, kindID: string, $namespace: string, annotationKeys: string[] | null): $CancellablePromise<$models.ResourceTable> {
    return $Call.ByID(2074631175, clusterID, kindID, $namespace, annotationKeys);
}

/**
 * NamespaceInventory reports what one namespace holds, kind by kind.
 * 
 * One request per built-in namespaced kind, so it is called when a panel's
 * section is opened rather than on every refresh — the counts are cheap
 * individually and there are twenty of them.
 */
export function NamespaceInventory(clusterID: string, $namespace: string): $CancellablePromise<$models.NamespaceInventory> {
    return $Call.ByID(1534543808, clusterID, $namespace);
}

/**
 * ObjectGraph returns the neighbourhood map of one object of any kind.
 * 
 * The third map shape, and the one that covers everything the generic table
 * lists. Bound beside GetManifest rather than beside the other two maps
 * because it is keyed the same way — by a navigator catalogue id, which is
 * what turns "whatever the drawer has open" into a kind that can be read.
 * 
 * Called when a map pane opens and never on a refresh tick: a neighbourhood
 * changes when somebody changes it, and redrawing a map under a reader is
 * worse than it being a few seconds stale.
 */
export function ObjectGraph(clusterID: string, kindID: string, $namespace: string, name: string): $CancellablePromise<$models.PodGraph> {
    return $Call.ByID(2301356998, clusterID, kindID, $namespace, name);
}

/**
 * RevealSecretKey returns one decoded Secret value, for a deliberate reveal.
 * 
 * Bound as its own narrow method rather than folded into anything the UI
 * calls on its own. Nothing in PodSteer reaches this except a person clicking
 * to reveal one key, which is what keeps each entry in a cluster's audit log
 * interpretable — a client that resolved every referenced Secret when a pane
 * opened would produce the exact burst pattern Kubernetes' Secret
 * good-practices page tells operators to alert on.
 * 
 * The returned value is never logged, never cached and never written to a
 * crash report: apiError below records the operation and the error, and the
 * error from the layers underneath carries the key name at most.
 */
export function RevealSecretKey(clusterID: string, $namespace: string, name: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(2496667775, clusterID, $namespace, name, key);
}

/**
 * VulnerabilitySummaries returns what a vulnerability scanner already running
 * in the cluster has recorded about one namespace's workloads.
 * 
 * CALLED ON ITS OWN, NEVER FROM A LIST. The pod list is drawn without it and
 * the chips fill in when this answers; a cluster with no scanner returns an
 * empty slice and the list is exactly what it was before this existed. See
 * ports.ResourcePort.ListVulnerabilitySummaries and the adapter's cache for
 * why this must never ride the refresh tick.
 */
export function VulnerabilitySummaries(clusterID: string, $namespace: string): $CancellablePromise<$models.VulnerabilitySummary[] | null> {
    return $Call.ByID(119269035, clusterID, $namespace);
}
