// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClusterAPI exposes the cluster use cases to the frontend.
 * 
 * Registered as a Wails service, which binds every exported method as
 * `ClusterAPI.ListClusters()` and so on and generates matching TypeScript from
 * the source. Method names and signatures are therefore public API.
 * 
 * Every method that touches a cluster takes its id: the UI holds one tab per
 * connected cluster and the backend keeps no notion of which one is in front.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddKubeconfig adds the given kubeconfig to the local one.
 */
export function AddKubeconfig(raw: string): $CancellablePromise<$models.KubeconfigMerge> {
    return $Call.ByID(1308384545, raw);
}

/**
 * CancelConnect stops a connect attempt that is still in the air.
 * 
 * NOTHING IN FLIGHT IS NOT AN ERROR. The attempt may have finished between the
 * operator pressing the control and this call arriving — a race the UI should
 * not have to handle, and one where the honest answer is that there is nothing
 * left to stop. Reported the same way Disconnect reports a cluster that is
 * already gone.
 */
export function CancelConnect(clusterID: string): $CancellablePromise<void> {
    return $Call.ByID(481441393, clusterID);
}

/**
 * Connect opens a cluster and returns it enriched with its server version.
 * 
 * Connecting an already open cluster refreshes it rather than failing, so the
 * frontend can call this to reconnect a tab whose credentials expired.
 * 
 * EVERY ATTEMPT IS CANCELLABLE AND NONE OF THEM WAIT FOR EACH OTHER. Wails
 * runs each call on its own goroutine, so several clusters were always able to
 * connect at once; what was missing was a way to STOP one. A cluster behind a
 * link that drops packets rather than refusing them takes the full request
 * timeout to fail, and until it did, the operator had a control they could not
 * take back. The attempt is registered here and CancelConnect below is what
 * takes it back.
 */
export function Connect(clusterID: string): $CancellablePromise<$models.Cluster> {
    return $Call.ByID(2487656719, clusterID);
}

/**
 * Connections returns the open clusters, in the order they were opened.
 * 
 * The frontend rebuilds its tab bar from this, which is why the order must be
 * stable: tabs that reshuffle are how somebody acts on the wrong cluster.
 */
export function Connections(): $CancellablePromise<$models.Cluster[] | null> {
    return $Call.ByID(454301032);
}

/**
 * Disconnect closes a cluster, for when the operator closes its tab.
 */
export function Disconnect(clusterID: string): $CancellablePromise<void> {
    return $Call.ByID(4037649153, clusterID);
}

/**
 * ListClusters returns every cluster in the local kubeconfig.
 * 
 * This is the one call that works before anything is connected, so it is what
 * the frontend uses to populate the cluster picker at launch. Clusters already
 * open are returned carrying their version, so the picker can mark them.
 */
export function ListClusters(): $CancellablePromise<$models.Cluster[] | null> {
    return $Call.ByID(1685875288);
}

/**
 * ListNamespaceSummaries returns every namespace with what is running in it.
 * 
 * Separate from ListNamespaces, which feeds the namespace filter and must stay
 * a cheap read of names: this one lists every pod in the cluster to count
 * them, and only the namespace list view is worth that.
 * 
 * annotationKeys names the annotations each row should carry — the same
 * projection WorkloadAPI.ListPods takes, for the same reason.
 */
export function ListNamespaceSummaries(clusterID: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null): $CancellablePromise<$models.NamespaceSummary[] | null> {
    return $Call.ByID(3424122106, clusterID, annotationKeys, expressions);
}

/**
 * ListNamespaces returns the namespaces of a connected cluster.
 */
export function ListNamespaces(clusterID: string): $CancellablePromise<$models.Namespace[] | null> {
    return $Call.ByID(2284935815, clusterID);
}

/**
 * ListNodes returns the nodes of a connected cluster, with usage where the
 * cluster provides metrics.
 * 
 * annotationKeys is the same projection ListNamespaceSummaries takes.
 */
export function ListNodes(clusterID: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null): $CancellablePromise<$models.Node[] | null> {
    return $Call.ByID(1549587712, clusterID, annotationKeys, expressions);
}

/**
 * PreviewKubeconfig reports what adding the given kubeconfig would change.
 * 
 * Separate from AddKubeconfig so the dialog can show what is about to happen
 * while the operator is still typing, without a keystroke ever being able to
 * write to the file.
 */
export function PreviewKubeconfig(raw: string): $CancellablePromise<$models.KubeconfigMerge> {
    return $Call.ByID(2564606126, raw);
}

/**
 * ReadKubeconfigFile opens a native file picker and returns what was chosen.
 * 
 * The file is read HERE rather than handed to the frontend as a path, because
 * the webview cannot open files — and should not be able to. An empty string
 * means the operator cancelled, which is not an error.
 */
export function ReadKubeconfigFile(): $CancellablePromise<string> {
    return $Call.ByID(3165107586);
}

/**
 * SetReadOnly marks a connected cluster read-only in PodSteer, or lifts the
 * mark.
 * 
 * A LOCAL GUARD, NOT A PERMISSION. The frontend calls this right after a
 * successful Connect and again whenever the group setting or the cluster's
 * group changes, and every write in ManagementService refuses while it is
 * set — but the flag lives here, in this process's memory, set by this
 * client. RBAC is what actually decides what the credentials behind this
 * connection may do; see SECURITY.md, "What PodSteer can do".
 */
export function SetReadOnly(clusterID: string, readOnly: boolean): $CancellablePromise<void> {
    return $Call.ByID(1325519139, clusterID, readOnly);
}
