// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileCopyAPI exposes copying files to and from a container, `kubectl cp`
 * from the pod drawer.
 * 
 * A transfer runs in its own goroutine, like a terminal session or a
 * port-forward, because it outlives any single call from the frontend:
 * StartDownload returns an id at once, progress and completion arrive as
 * events, and Cancel ends it early. Every transfer's goroutine has one owner
 * (this API), one way to stop (its context) and one exit (the "done" event).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(1306114370, transferID);
}

/**
 * ListDirectory lists one directory inside a container.
 * 
 * A READ THAT RUNS A SHELL, which is why it is refused on a cluster marked
 * read-only while the download beside it is not — see
 * ManagementService.ListDirectory for that reasoning.
 */
export function ListDirectory(clusterID: string, $namespace: string, podName: string, containerName: string, remoteDir: string): $CancellablePromise<$models.DirectoryListing> {
    return $Call.ByID(4207437331, clusterID, $namespace, podName, containerName, remoteDir);
}

/**
 * StartDownload copies remotePath out of a container into localDir, a
 * directory the operator chose through SystemAPI.ChooseDirectory, and
 * returns the transfer id.
 * 
 * The download lands under localDir by the remote entry's own name —
 * `/etc/nginx` becomes `<localDir>/nginx` — exactly as `kubectl cp
 * pod:/etc/nginx <localDir>/` would. Nothing is written anywhere the
 * operator did not pick, and nothing is written by the webview: every byte
 * goes through the ArchivePort's checks in Go.
 */
export function StartDownload(clusterID: string, $namespace: string, podName: string, containerName: string, remotePath: string, localDir: string): $CancellablePromise<string> {
    return $Call.ByID(1277171388, clusterID, $namespace, podName, containerName, remotePath, localDir);
}

/**
 * StartUpload copies localPath — a file or directory the operator chose
 * through SystemAPI.ChooseFile or ChooseDirectory — into remoteDir inside a
 * container, and returns the transfer id.
 * 
 * A write into the cluster's workload, so it gets the same synchronous
 * read-only refusal StartSession gives a shell, checked HERE before a
 * goroutine is started. ManagementService.UploadToPod checks again; this is
 * the fast path that avoids a transfer that would appear to start and
 * immediately fail.
 */
export function StartUpload(clusterID: string, $namespace: string, podName: string, containerName: string, localPath: string, remoteDir: string): $CancellablePromise<string> {
    return $Call.ByID(1306649429, clusterID, $namespace, podName, containerName, localPath, remoteDir);
}
