// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FleetAPI exposes the cross-cluster reads to the frontend.
 * 
 * One bridge call per tick per table, however many clusters are open: the
 * fan-out is on this side, and the frontend gets every cluster's rows and
 * every cluster's verdict in one answer, grouped per cluster in tab order.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListEvents lists events in the given namespace of each named cluster.
 */
export function ListEvents(clusterIDs: string[] | null, $namespace: string): $CancellablePromise<$models.ClusterEvents[] | null> {
    return $Call.ByID(2753285828, clusterIDs, $namespace);
}

/**
 * ListPods lists pods in the given namespace of each named cluster.
 * 
 * An empty namespace lists across all of them in every cluster; a named one
 * is looked for in every cluster, and a cluster that does not have it simply
 * contributes no rows.
 */
export function ListPods(clusterIDs: string[] | null, $namespace: string): $CancellablePromise<$models.ClusterPods[] | null> {
    return $Call.ByID(259102093, clusterIDs, $namespace);
}

/**
 * ListWorkloads lists every fleet workload kind in the given namespace of
 * each named cluster.
 */
export function ListWorkloads(clusterIDs: string[] | null, $namespace: string): $CancellablePromise<$models.ClusterWorkloads[] | null> {
    return $Call.ByID(1060283261, clusterIDs, $namespace);
}
