// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HelmAPI exposes what Helm has installed.
 * 
 * ONE METHOD, IT IS A READ, AND IT IS NEVER ON THE REFRESH TICK. The page
 * calls it when it opens and when somebody presses Refresh, and nothing else
 * does. A navigator entry on the ordinary ten-second poll would issue a
 * metadata LIST of Secrets every ten seconds — six `list secrets` lines a
 * minute in the operator's audit log for as long as the page were left open,
 * which is the Secrets doctrine's own signature with the bytes removed and
 * the pattern intact.
 * 
 * NOTHING HERE READS A RELEASE PAYLOAD. The list is built entirely from the
 * labels Helm puts on each release Secret, through the metadata client, so no
 * Secret contents cross the wire at all. Reading a payload is a separate,
 * explicitly-clicked act with its own controls and is deliberately not on
 * this surface yet.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListReleases returns what Helm has installed in one namespace, or
 * cluster-wide when the namespace is blank or selects every namespace.
 * 
 * Being refused is an ordinary answer and arrives as a STATUS on the listing
 * rather than as a rejection, so the pane renders with a sentence naming the
 * permission instead of blanking. A cluster with no Helm releases is a
 * successful listing with zero rows, which is a different answer and reads as
 * one.
 * 
 * refresh bypasses the five-minute cache for this one call. The page's own
 * Refresh control passes true; the page's first load passes false, and
 * NOTHING on a timer calls this method at all.
 */
export function ListReleases(clusterID: string, $namespace: string, refresh: boolean): $CancellablePromise<$models.HelmListing> {
    return $Call.ByID(3633651165, clusterID, $namespace, refresh);
}

/**
 * ReadRelease reads ONE revision of ONE release, because somebody clicked.
 * 
 * THE SECOND METHOD ON THIS SURFACE, AND A DIFFERENT ACT FROM THE FIRST.
 * ListReleases transfers no Secret contents whatsoever; this reads a release
 * payload whole, which is the act the Secrets doctrine governs. So it is
 * shaped exactly as RevealSecretKey is: it happens because somebody pressed
 * something, on one named revision, and it is audited in the application
 * layer by cluster, namespace, release and revision — never a value.
 * 
 * NOTHING MAY EVER CALL THIS ON RENDER OR ON A TICK. The page calls it from
 * a button's handler and from nowhere else; a $effect that reached it would
 * turn opening a drawer into a Secret read, which is the pattern Kubernetes'
 * own guidance tells cluster operators to alert on and the exact thing this
 * whole feature was permitted on the condition of not doing.
 * 
 * A FAILURE IS A REJECTION HERE, unlike ListReleases where a refusal is an
 * ordinary answer carried beside the rows. There is nothing to render without
 * the payload, and an empty detail would let an empty values tab read as a
 * release installed with no values. The two new codes — helm_payload_too_large
 * and helm_payload_unreadable — and the Helm-specific not_found sentence are
 * in errors.go.
 */
export function ReadRelease(clusterID: string, $namespace: string, release: string, revision: number): $CancellablePromise<$models.HelmReleaseDetail> {
    return $Call.ByID(2950025808, clusterID, $namespace, release, revision);
}
