// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryAPI exposes the recorded history and its retention setting.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSeries returns a cluster's recorded history over the last windowMinutes.
 * 
 * maxPoints bounds what crosses the IPC boundary; the backend averages down to
 * it rather than dropping points, so a spike survives as a bump instead of
 * disappearing between the samples that happened to be kept.
 */
export function GetSeries(clusterID: string, windowMinutes: number, maxPoints: number): $CancellablePromise<$models.SeriesResult> {
    return $Call.ByID(3903375474, clusterID, windowMinutes, maxPoints);
}

/**
 * GetSettings reports what is recorded and how often.
 */
export function GetSettings(): $CancellablePromise<$models.HistorySettings> {
    return $Call.ByID(30476134);
}

/**
 * SetRetention changes how long samples are kept.
 * 
 * Zero turns recording off AND discards what has already been recorded, which
 * is what an operator means by it. Anything else would leave the previous
 * window's data sitting on disk after they asked for none.
 */
export function SetRetention(days: number): $CancellablePromise<void> {
    return $Call.ByID(2181828023, days);
}

/**
 * SetSamplingInterval changes how often each open cluster is sampled.
 * 
 * Every sample costs a full cluster assessment, so this is a real load control
 * on a large cluster and not only a chart-resolution preference. The value is
 * clamped to the supported range rather than rejected: an out-of-range cadence
 * is a UI bug, and refusing it would leave the operator with no recording at
 * all rather than a slightly different one.
 */
export function SetSamplingInterval(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(769714467, seconds);
}
