// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InspectAPI exposes the two on-request inspections.
 * 
 * NOTHING HERE IS ON THE REFRESH TICK, and that is the rule the whole surface
 * exists to make visible — see ports.InspectService. A probe is one act the
 * operator asked for; the panel above it shows the answer with the time it
 * was taken and waits to be asked again.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ImageReport describes one container's image from what Kubernetes reports.
 */
export function ImageReport(clusterID: string, $namespace: string, podName: string, containerName: string): $CancellablePromise<$models.ImageReport> {
    return $Call.ByID(586910148, clusterID, $namespace, podName, containerName);
}

/**
 * ProbeFromHere probes a target from this machine.
 * 
 * One act, one answer, never a tick. It reaches the cluster the only way this
 * process reaches anything — through the API server named in the kubeconfig —
 * and refuses outright for anything that would mean contacting a host that is
 * not one, which is why an Ingress offers only the in-cluster vantage.
 */
export function ProbeFromHere(clusterID: string, subject: $models.ProbeSubjectInput): $CancellablePromise<$models.ProbeResult> {
    return $Call.ByID(3739056027, clusterID, subject);
}

/**
 * ProbeFromPod probes a target from inside a container the operator chose.
 * 
 * A WRITE-SHAPED ACT: it runs a command in somebody's container, so it is
 * refused on a cluster marked read-only and leaves one audit line naming the
 * cluster, namespace, pod, container and target. What it never records is
 * what came back.
 */
export function ProbeFromPod(clusterID: string, $namespace: string, podName: string, containerName: string, subject: $models.ProbeSubjectInput): $CancellablePromise<$models.ProbeResult> {
    return $Call.ByID(2473744860, clusterID, $namespace, podName, containerName, subject);
}
