// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ManagementAPI exposes management operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortRollout abandons the update an Argo Rollouts Rollout is part way
 * through, the way `kubectl argo rollouts abort NAME` does.
 */
export function AbortRollout(clusterID: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2237036739, clusterID, $namespace, name);
}

/**
 * BulkCordon marks every selected node unschedulable (cordon true) or
 * schedulable again (cordon false), and reports each outcome.
 */
export function BulkCordon(clusterID: string, items: $models.BulkItemDTO[] | null, cordon: boolean): $CancellablePromise<$models.BulkResultDTO[] | null> {
    return $Call.ByID(2912970621, clusterID, items, cordon);
}

/**
 * BulkDelete deletes every selected object the plan allows, and reports each
 * outcome.
 */
export function BulkDelete(clusterID: string, items: $models.BulkItemDTO[] | null): $CancellablePromise<$models.BulkResultDTO[] | null> {
    return $Call.ByID(754751891, clusterID, items);
}

/**
 * BulkRestart triggers a rolling restart of every selected Deployment,
 * StatefulSet and DaemonSet, and reports each outcome.
 */
export function BulkRestart(clusterID: string, items: $models.BulkItemDTO[] | null): $CancellablePromise<$models.BulkResultDTO[] | null> {
    return $Call.ByID(1616204547, clusterID, items);
}

/**
 * BulkScale sets replicas on every selected Deployment, StatefulSet and
 * ReplicaSet, and reports each outcome.
 */
export function BulkScale(clusterID: string, items: $models.BulkItemDTO[] | null, replicas: number): $CancellablePromise<$models.BulkResultDTO[] | null> {
    return $Call.ByID(2554722730, clusterID, items, replicas);
}

/**
 * CordonNode marks a node schedulable or unschedulable.
 */
export function CordonNode(clusterID: string, name: string, cordon: boolean): $CancellablePromise<void> {
    return $Call.ByID(3886147145, clusterID, name, cordon);
}

/**
 * DeleteResource deletes a single resource.
 */
export function DeleteResource(clusterID: string, kindGroup: string, kindVersion: string, kindKind: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2285095283, clusterID, kindGroup, kindVersion, kindKind, $namespace, name);
}

/**
 * DrainNode cordons a node and evicts every pod the drain plan allows.
 * 
 * timeoutSeconds of zero or less means the adapter's own default. A negative
 * gracePeriodSeconds means "use each pod's own
 * terminationGracePeriodSeconds", the same convention `kubectl drain
 * --grace-period` uses.
 */
export function DrainNode(clusterID: string, name: string, force: boolean, deleteEmptyDirData: boolean, gracePeriodSeconds: number, timeoutSeconds: number): $CancellablePromise<$models.DrainReportDTO> {
    return $Call.ByID(819325490, clusterID, name, force, deleteEmptyDirData, gracePeriodSeconds, timeoutSeconds);
}

/**
 * EvictPod evicts one pod through the eviction subresource, which a
 * PodDisruptionBudget may refuse — see ports.ErrDisruptionBudget.
 */
export function EvictPod(clusterID: string, $namespace: string, name: string, gracePeriodSeconds: number): $CancellablePromise<void> {
    return $Call.ByID(1078496148, clusterID, $namespace, name, gracePeriodSeconds);
}

/**
 * ExecInPod executes a command in a pod container.
 * 
 * This is a simplified version that runs a command and returns the output.
 * For interactive terminal sessions, use the WebSocket-based exec endpoint.
 */
export function ExecInPod(clusterID: string, $namespace: string, podName: string, containerName: string, command: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(489175841, clusterID, $namespace, podName, containerName, command);
}

/**
 * FreeLocalPort asks the operating system for a local TCP port nothing is
 * using, so the "Pick a free port" control can offer one instead of asking
 * the operator to guess.
 */
export function FreeLocalPort(): $CancellablePromise<number> {
    return $Call.ByID(1404535818);
}

/**
 * ListNodeShells reports the node shells running right now — the live
 * registry, exactly like ListPortForwards, so the activity list shows only
 * pods that still exist rather than a record of ones that were asked for.
 */
export function ListNodeShells(): $CancellablePromise<$models.NodeShell[] | null> {
    return $Call.ByID(2508393379);
}

/**
 * ListPortForwards reports what is forwarded right now.
 * 
 * The list is the live registry, not a record of intent. A forward appears
 * here because a goroutine is holding its socket — which is the difference
 * between this and the clients where a forward shows as active after its
 * connection died, and the stop button does nothing because there is nothing
 * left to stop.
 */
export function ListPortForwards(): $CancellablePromise<$models.PortForward[] | null> {
    return $Call.ByID(3952666381);
}

/**
 * PlanBulk previews what a bulk action would do to items, without touching
 * the cluster — the same domain.PlanBulk the Bulk* methods below run, so the
 * review dialog and the run it precedes can never disagree. The cluster's
 * read-only flag is read here so a read-only cluster's preview says so on
 * every line, before the operator confirms into a refusal.
 * 
 * replicas is read for the scale action only.
 */
export function PlanBulk(clusterID: string, action: string, items: $models.BulkItemDTO[] | null, replicas: number): $CancellablePromise<$models.BulkPlanDTO> {
    return $Call.ByID(3107260351, clusterID, action, items, replicas);
}

/**
 * PlanDrain previews what draining name would do, without touching the
 * cluster — the candidates a drain of this node would consider, run through
 * the same domain.PlanDrain a real drain uses, so the preview and the drain
 * it precedes can never disagree.
 */
export function PlanDrain(clusterID: string, name: string, force: boolean, deleteEmptyDirData: boolean): $CancellablePromise<$models.DrainPlanDTO> {
    return $Call.ByID(2002179927, clusterID, name, force, deleteEmptyDirData);
}

/**
 * ProbeLocalPort reports whether a TCP port on THIS machine — never the
 * cluster — is free to bind.
 * 
 * Placed beside the other port-forward calls rather than on SystemAPI: it
 * exists purely to serve the local-port picker in the forward-start UI, the
 * transport it is asking about is the same forwards.PortForwardPort this
 * struct already holds, and splitting "local port" concerns across two bound
 * APIs over a single feature would cost the frontend two imports for one
 * idea. It never touches a cluster.
 */
export function ProbeLocalPort(port: number): $CancellablePromise<boolean> {
    return $Call.ByID(131752118, port);
}

/**
 * PromoteRollout advances a paused Argo Rollouts Rollout by one step, the
 * way `kubectl argo rollouts promote NAME` does.
 * 
 * The read-only refusal, the audit line and the patch decision all happen
 * below this — see ManagementService.PromoteRollout and
 * domain.PlanRolloutPromote. This is the ordinary bound write; nothing about
 * it is special except the kind it acts on.
 */
export function PromoteRollout(clusterID: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(243262621, clusterID, $namespace, name);
}

/**
 * RestartRollout triggers a rolling restart of a Deployment or StatefulSet.
 */
export function RestartRollout(clusterID: string, kind: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(472073868, clusterID, kind, $namespace, name);
}

/**
 * RollbackWorkload rolls a Deployment, StatefulSet or DaemonSet back to a
 * previously recorded revision, the way `kubectl rollout undo
 * --to-revision` does. dryRun asks the API server to validate the request
 * without persisting anything — RollbackDialog's Preview button — and is
 * allowed on a read-only cluster for the same reason ValidateResource is.
 */
export function RollbackWorkload(clusterID: string, kind: string, $namespace: string, name: string, toRevision: number, dryRun: boolean): $CancellablePromise<$models.RollbackOutcomeDTO> {
    return $Call.ByID(585813657, clusterID, kind, $namespace, name, toRevision, dryRun);
}

/**
 * ScaleWorkload sets the replica count for a workload.
 */
export function ScaleWorkload(clusterID: string, kind: string, $namespace: string, name: string, replicas: number): $CancellablePromise<void> {
    return $Call.ByID(2913691339, clusterID, kind, $namespace, name, replicas);
}

/**
 * SetConfigMapKey writes one key of one ConfigMap.
 */
export function SetConfigMapKey(clusterID: string, $namespace: string, name: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4012453211, clusterID, $namespace, name, key, value);
}

/**
 * SetImage sets one container's (or, when initContainer is true, one init
 * container's) image on a Deployment, StatefulSet or DaemonSet.
 */
export function SetImage(clusterID: string, kind: string, $namespace: string, name: string, container: string, image: string, initContainer: boolean): $CancellablePromise<void> {
    return $Call.ByID(2761830097, clusterID, kind, $namespace, name, container, image, initContainer);
}

/**
 * SetSecretKey writes one key of one Secret.
 * 
 * value is the operator's typed, decoded text — not base64 — converted to
 * bytes here rather than asking the frontend to encode anything, mirroring
 * how RevealSecretKey hands back the decoded string in the other direction.
 * 
 * Bound as its own narrow method for the same reason RevealSecretKey is: it
 * is only ever called from a deliberate Save on a key the operator has
 * already revealed, which is what keeps each entry in a cluster's audit log
 * interpretable. See web/src/lib/components/ContainerDetail.svelte and
 * CLAUDE.md's "Secrets are read on request, never on render".
 */
export function SetSecretKey(clusterID: string, $namespace: string, name: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2852015863, clusterID, $namespace, name, key, value);
}

/**
 * StartPortForward opens a local port onto a container port.
 * 
 * localPort may be zero, in which case the operating system chooses and the
 * returned forward carries what it chose. That is the honest default: asking
 * somebody to pick a free port is asking them to guess, and a collision is
 * reported as a failure to start rather than silently moved somewhere else.
 */
export function StartPortForward(clusterID: string, $namespace: string, pod: string, podUID: string, localPort: number, remotePort: number, portName: string, protocol: string, selector: { [_ in string]?: string } | null): $CancellablePromise<$models.PortForward> {
    return $Call.ByID(869938752, clusterID, $namespace, pod, podUID, localPort, remotePort, portName, protocol, selector);
}

/**
 * StopAllNodeShells deletes every node-shell pod, across every cluster — the
 * "Stop all" companion for node shells, and what the composition root calls on
 * shutdown so nothing privileged is left running on a node.
 */
export function StopAllNodeShells(): $CancellablePromise<void> {
    return $Call.ByID(4039059488);
}

/**
 * StopAllPortForwards closes every running forward, across every cluster,
 * and waits for each local port to be released before returning.
 * 
 * Previously reachable only from OnShutdown, where nothing was waiting on the
 * answer. The "Stop all" control in the forwards panel needs the same
 * guarantee StopPortForward already makes for one forward — that the port is
 * free before the call returns — which the underlying registry teardown
 * already provides; this only exposes it.
 */
export function StopAllPortForwards(): $CancellablePromise<void> {
    return $Call.ByID(1363765426);
}

/**
 * StopLogStream cancels a log stream.
 * 
 * The streamID is returned by StreamLogs. Calling this on an already-stopped
 * stream is a no-op.
 */
export function StopLogStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(1227638758, streamID);
}

/**
 * StopNodeShell deletes the pod behind one node shell — the stop control in
 * the activity list. The attach session ending deletes the pod on its own, so
 * this and that both reaching the same shell is not an error.
 */
export function StopNodeShell(shellID: string): $CancellablePromise<void> {
    return $Call.ByID(2041131346, shellID);
}

/**
 * StopPortForward closes one forward.
 */
export function StopPortForward(forwardID: string): $CancellablePromise<void> {
    return $Call.ByID(2275040476, forwardID);
}

/**
 * StreamLogs streams pod logs to the frontend via events.
 * 
 * The frontend must subscribe to "log:lines" events to receive log lines.
 * Each event payload is a LogLinesEvent carrying a BATCH of lines — see the
 * batcher below for why they are not sent one at a time.
 * The stream ends when the pod terminates, the context is cancelled, or an
 * error occurs. A "log:end" event is emitted when the stream closes.
 * 
 * sinceSeconds and limitBytes of 0 mean unset, matching domain.LogOptions —
 * see its doc comment for what each parameter does. timestamps is always
 * sent true by the frontend today: it decides whether to DISPLAY a
 * timestamp at render time rather than by re-opening the stream, so the
 * parameter exists here for the same reason it exists on domain.LogOptions,
 * not because any caller currently varies it.
 */
export function StreamLogs(clusterID: string, $namespace: string, podName: string, containerName: string, follow: boolean, tailLines: number, sinceSeconds: number, previous: boolean, timestamps: boolean, limitBytes: number): $CancellablePromise<string> {
    return $Call.ByID(2086826255, clusterID, $namespace, podName, containerName, follow, tailLines, sinceSeconds, previous, timestamps, limitBytes);
}

/**
 * SuspendWorkload sets or clears suspend on a CronJob or a Job.
 */
export function SuspendWorkload(clusterID: string, kind: string, $namespace: string, name: string, suspend: boolean): $CancellablePromise<void> {
    return $Call.ByID(2001011585, clusterID, kind, $namespace, name, suspend);
}

/**
 * TriggerCronJob creates a Job from a CronJob's template right now, outside
 * its schedule, and returns the created Job's name.
 */
export function TriggerCronJob(clusterID: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2754745055, clusterID, $namespace, name);
}

/**
 * UpdateResource applies a YAML manifest of any kind to the cluster — the
 * generic path through the dynamic client, not a fixed set of typed kinds.
 * See ports.ManagementPort.UpdateResource for the full contract: a manifest
 * carrying metadata.resourceVersion is sent as a PUT the server optimistic-
 * locks against (a stale version comes back as the "conflict" error code);
 * one without it is created, replacing an existing object of the same name.
 */
export function UpdateResource(clusterID: string, manifest: string): $CancellablePromise<$models.ApplyOutcomeDTO> {
    return $Call.ByID(1990144045, clusterID, manifest);
}

/**
 * ValidateResource is UpdateResource's dry run: the manifest is sent through
 * the same generic apply path with DryRun=All, so the API server runs every
 * admission check (schema validation, webhooks) without persisting anything.
 * Allowed on a read-only cluster — see ManagementService.UpdateResource's own
 * comment on why — which is what lets an operator check a manifest is
 * well-formed before asking someone with write access to apply it for real.
 */
export function ValidateResource(clusterID: string, manifest: string): $CancellablePromise<$models.ApplyOutcomeDTO> {
    return $Call.ByID(2813971106, clusterID, manifest);
}
