// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetricsQueryAPI exposes the monitoring-backend read to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSeries asks the cluster's monitoring backend for one metric over a
 * window.
 * 
 * NEVER CALLED FROM A REFRESH TICK. The rule lives with the caller — see
 * web/src/stores/backendTrend.svelte.ts, whose test counts calls across
 * several driven refreshes — because a tick is this application deciding on
 * its own to put PromQL onto somebody's production Prometheus, and a chart
 * opening is somebody looking at something.
 * 
 * There is NO EXPRESSION PARAMETER, and there never will be one: the metric
 * and the scope select from a fixed table in the domain, so no string an
 * operator wrote can reach a backend.
 */
export function GetSeries(clusterID: string, metric: string, scope: string, windowMinutes: number): $CancellablePromise<$models.BackendSeriesResult> {
    return $Call.ByID(971685041, clusterID, metric, scope, windowMinutes);
}
