// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccessDecision is the API server's answer to one question.
 */
export interface AccessDecision {
    /**
     * Request is the question, echoed so an answer cannot be read against a
     * form that has since been edited.
     */
    "request": AccessRequest;

    /**
     * Status is answered, forbidden, absent or failed.
     */
    "status": string;

    /**
     * Refusal is the sentence to show when Status is not "answered".
     */
    "refusal": string;

    /**
     * Allowed is the API server's own `allowed`.
     */
    "allowed": boolean;

    /**
     * Denied is the API server's own `denied`. NOT the opposite of Allowed:
     * an authorizer with no opinion leaves both false, which is a third
     * answer and must render as one.
     */
    "denied": boolean;

    /**
     * Reason is the API server's own `reason`, verbatim.
     */
    "reason": string;

    /**
     * EvaluationError is the API server's own `evaluationError`, verbatim.
     */
    "evaluationError": string;
}

/**
 * AccessRequest is one "can I" question.
 * 
 * The subject is FLATTENED into three strings rather than nested, unlike
 * everywhere else here, because this type is an ARGUMENT: Wails generates a
 * class with a value-converting method for any struct holding another, and a
 * plain object typed against it no longer satisfies the declaration the
 * frontend has to call through. Three fields cost nothing and keep the call
 * site an object literal.
 */
export interface AccessRequest {
    /**
     * SubjectKind is "User", "Group" or "ServiceAccount". Empty, with an
     * empty SubjectName, asks about the current account — which is a
     * different review API rather than a missing field.
     */
    "subjectKind": string;

    /**
     * SubjectName is the account being asked about.
     */
    "subjectName": string;

    /**
     * SubjectNamespace is a ServiceAccount subject's namespace.
     */
    "subjectNamespace": string;

    /**
     * Verb is the action, e.g. "create". Required.
     */
    "verb": string;

    /**
     * Group is the API group, empty for the core group.
     */
    "group": string;

    /**
     * Resource is the resource plural, e.g. "pods". Required.
     */
    "resource": string;

    /**
     * Subresource narrows it, e.g. "log" or "exec".
     */
    "subresource": string;

    /**
     * Namespace scopes the question; empty asks at cluster scope.
     */
    "namespace": string;

    /**
     * Name narrows the question to one object.
     */
    "name": string;
}

/**
 * AppInfo describes the running application to the UI.
 * 
 * It exists so the status bar can show a version without the frontend
 * hard-coding one — a hard-coded version is a version that is wrong the moment
 * somebody cuts a release.
 */
export interface AppInfo {
    /**
     * Name is the short application name.
     */
    "name": string;

    /**
     * Version is the release version, set at build time via -ldflags.
     */
    "version": string;

    /**
     * Platform is the OS and architecture the binary was built for.
     */
    "platform": string;

    /**
     * Website is the project's home page.
     */
    "website": string;
}

/**
 * Application is one deployed instance and what it is made of.
 */
export interface Application {
    /**
     * Instance is the app.kubernetes.io/instance label — the identity.
     */
    "instance": string;
    "namespace": string;

    /**
     * PartOf, Name, ManagedBy and Version are the other recommended labels,
     * empty when nothing carries them.
     */
    "partOf": string;
    "name": string;
    "managedBy": string;
    "version": string;

    /**
     * Members are the kinds it is made of, largest first.
     */
    "members": ApplicationMember[] | null;

    /**
     * Objects is how many it holds in total.
     */
    "objects": number;

    /**
     * Pods is how many pods the figures cover, MeasuredPods how many of those
     * reported a measurement. Fewer measured than pods means the total is
     * real and short.
     */
    "pods": number;
    "measuredPods": number;

    /**
     * MeasurablePods is how many COULD be measured — the ones on a node.
     * metrics-server never reports a finished or unscheduled pod, so this is
     * the denominator for "is this total short", not Pods.
     */
    "measurablePods": number;

    /**
     * HasMetrics is whether there are figures to draw.
     */
    "hasMetrics": boolean;

    /**
     * MetricsAvailable is whether the CLUSTER serves metrics at all.
     * 
     * The UI must not collapse the two. An idle namespace on a metered
     * cluster and a cluster with no metrics-server both measure nothing, and
     * telling somebody to install one when they already have it is the bug
     * this field exists to prevent.
     */
    "metricsAvailable": boolean;

    /**
     * CPU and Memory are what the pods are using, formatted.
     */
    "cpu": string;
    "memory": string;

    /**
     * The reference figures, formatted.
     */
    "cpuRequest": string;
    "memoryRequest": string;
    "cpuLimit": string;
    "memoryLimit": string;

    /**
     * Whether there is a denominator at all. A zero percentage cannot stand
     * in for these: a set of pods that DID reserve CPU and is idle also reads
     * 0%, and the two must not draw the same thing.
     */
    "hasCpuRequest": boolean;
    "hasMemoryRequest": boolean;
    "hasCpuLimit": boolean;
    "hasMemoryLimit": boolean;

    /**
     * Usage as a percentage of the request, and of the limit. The first says
     * whether the reservation was right; only the second predicts throttling
     * or a kill.
     */
    "cpuPercent": number;
    "memoryPercent": number;
    "cpuLimitPercent": number;
    "memoryLimitPercent": number;

    /**
     * The same figures raw, for sorting a column and plotting a chart: CPU in
     * cores, memory in bytes.
     */
    "cpuCores": number;
    "memoryBytes": number;
    "requestCores": number;
    "requestBytes": number;
    "limitCores": number;
    "limitBytes": number;
}

/**
 * ApplicationInventory is every application found, and what was not.
 */
export interface ApplicationInventory {
    "applications": Application[] | null;

    /**
     * Unlabelled is how many objects carried no instance label.
     * 
     * The UI must show it. The labels are a convention rather than a
     * guarantee, and a view that silently omits what does not carry them is
     * worse than no view because it looks complete.
     */
    "unlabelled": number;
}

/**
 * ApplicationMember is one kind's contribution to an application.
 */
export interface ApplicationMember {
    "kind": string;
    "count": number;
}

/**
 * ApplyOutcomeDTO reports what UpdateResource or ValidateResource actually
 * did — what domain.ApplyOutcome carries, over the wire.
 */
export interface ApplyOutcomeDTO {
    /**
     * Created is true when the object did not exist and was created; false
     * when an existing object was replaced.
     */
    "created": boolean;

    /**
     * Kind is the applied object's Kubernetes kind, e.g. "Deployment".
     */
    "kind": string;

    /**
     * Name is the applied object's name.
     */
    "name": string;

    /**
     * Namespace is empty for a cluster-scoped kind.
     */
    "namespace": string;

    /**
     * DryRun reports whether this outcome came from a server-side dry run —
     * ValidateResource always sets it; UpdateResource never does. Nothing
     * was persisted when it is true.
     */
    "dryRun": boolean;

    /**
     * Warnings carries any warning the API server attached to the request.
     * Always empty today — see Adapter.UpdateResource's own comment on why —
     * but present on the wire so the frontend does not need a second shape
     * once it is wired.
     */
    "warnings": string[] | null;
}

/**
 * BulkItemDTO is one selected row, as the frontend hands it back for a bulk
 * action: the object's coordinates plus the facts domain.PlanBulk reads.
 * 
 * Each fact is a QUOTATION of a field the row already carries — a pod's
 * "Controlled By" split back into kind and name, a workload's desired count,
 * a node's cordoned flag — so planning a selection costs no read at all.
 * Absent facts (a generic table row knows no owner) arrive as their zero
 * values and produce no note, never a guess.
 */
export interface BulkItemDTO {
    /**
     * Group, Version and Kind identify the object's kind; the core group is
     * empty, per domain.ResourceKind.
     */
    "group": string;
    "version": string;
    "kind": string;

    /**
     * Namespace is empty for a cluster-scoped object.
     */
    "namespace": string;
    "name": string;

    /**
     * ControllerKind and ControllerName are the controlling ownerReference,
     * both empty when the object has none or the row did not know.
     */
    "controllerKind": string;
    "controllerName": string;

    /**
     * Replicas is the current desired replica count, read for scale only.
     */
    "replicas": number;

    /**
     * Unschedulable reports a node is cordoned, read for cordon only.
     */
    "unschedulable": boolean;
}

/**
 * BulkLineDTO is one object's verdict in a bulk plan — what PlanBulk decided
 * for it, over the wire.
 */
export interface BulkLineDTO {
    "kind": string;
    "namespace": string;
    "name": string;

    /**
     * Act reports whether the action will be attempted on this object.
     */
    "act": boolean;

    /**
     * Reason says why the object is skipped; empty when Act is true.
     */
    "reason": string;

    /**
     * Note is what else happens when it acts — a controller that will
     * recreate a deleted object, the count a scale moves from and to. Empty
     * when there is nothing to add.
     */
    "note": string;
}

/**
 * BulkPlanDTO previews what a bulk action would do, without doing it — what
 * PlanBulk returns, over the wire. Acting and Skipped are counted here rather
 * than re-derived from Lines by the frontend, so the domain's own rule is the
 * one place that decides.
 */
export interface BulkPlanDTO {
    "action": string;
    "lines": BulkLineDTO[] | null;
    "acting": number;
    "skipped": number;
}

/**
 * BulkResultDTO is what happened to one object when a bulk action ran — one
 * per selected row, in the selection's order, whether it was skipped, done,
 * or failed.
 */
export interface BulkResultDTO {
    "kind": string;
    "namespace": string;
    "name": string;

    /**
     * Skipped reports the plan left the object alone; Reason says why.
     */
    "skipped": boolean;

    /**
     * Done reports the write succeeded. False with Skipped false means it
     * failed, and Code and Reason say how.
     */
    "done": boolean;

    /**
     * Reason is the skip reason, or the failure's operator-facing message —
     * the same sentence a single write's error would carry, produced by the
     * same classification.
     */
    "reason": string;

    /**
     * Note carries the plan line's note through.
     */
    "note": string;

    /**
     * Code is the failure's ErrorCode, the same the frontend parses out of a
     * single write's rejected promise; empty unless the write failed.
     */
    "code": string;
}

/**
 * CapacitySummary is the cluster's capacity across every dimension.
 */
export interface CapacitySummary {
    "cpu": ResourceUsage;
    "memory": ResourceUsage;
    "ephemeral": ResourceUsage;
    "pods": PodCapacity;
}

/**
 * Certificate is one X.509 certificate as shown by a Secret's certificate
 * inspection — see BrowseAPI.InspectTLSSecret. Never sent except in answer to
 * that deliberate call.
 */
export interface Certificate {
    "subject": string;
    "issuer": string;
    "sans": string[] | null;

    /**
     * NotBefore and NotAfter are RFC 3339, in UTC.
     */
    "notBefore": string;
    "notAfter": string;

    /**
     * ExpiresInSeconds is NotAfter minus the time InspectTLSSecret ran, so
     * the frontend never re-derives it from parsing NotAfter itself.
     * Negative once the certificate has expired.
     */
    "expiresInSeconds": number;
    "serialNumber": string;
    "signatureAlgorithm": string;
    "publicKeyAlgorithm": string;
    "keyBits": number;
    "isCA": boolean;
    "selfSigned": boolean;
}

/**
 * CertificateChainDTO is one Secret's parsed certificate material, returned
 * only from a deliberate InspectTLSSecret call — never from GetManifest and
 * never on render.
 */
export interface CertificateChainDTO {
    "leaf": Certificate;
    "intermediates": Certificate[] | null;

    /**
     * KeyMatches is null when no key was inspected at all — a Secret
     * carrying ca.crt with no tls.key, say — which is a different fact from
     * false and must not be collapsed into it.
     */
    "keyMatches": boolean | null;

    /**
     * Insights are AssessPod's counterpart for a certificate. See
     * domain.CertificateFindings.
     */
    "insights": CertificateInsight[] | null;
}

/**
 * CertificateInsight is one thing worth telling an operator about an
 * inspected certificate chain — the certificate equivalent of PodFinding.
 */
export interface CertificateInsight {
    "severity": string;
    "title": string;
    "detail": string;
    "advice": string;
}

/**
 * CertificateRenewalRef is what a cert-manager Certificate's status says
 * about its own expiry, as the panel read it off the manifest it already
 * holds.
 * 
 * The certificate equivalent of ConditionRef, and here for the same reason:
 * the panel is pure quotation, but "this is running out and nothing is
 * renewing it" is a COMPARISON against the clock, and comparisons are
 * verdicts that live in the Go domain where a test can argue with them. The
 * timestamps cross as RFC 3339 strings — what the object itself carries — and
 * one that does not parse is treated as absent rather than as an error, since
 * the panel is showing that same field verbatim beside this.
 */
export interface CertificateRenewalRef {
    /**
     * NotAfter and RenewalTime are status.notAfter and status.renewalTime.
     * Empty is meaningful for both: nothing issued yet, and no renewal
     * scheduled.
     */
    "notAfter": string;
    "renewalTime": string;

    /**
     * ReadyStatus and ReadyReason are the Ready condition's own words.
     */
    "readyStatus": string;
    "readyReason": string;

    /**
     * IssuingStatus is the Issuing condition's status, "True" while a
     * (re)issuance is in flight.
     */
    "issuingStatus": string;

    /**
     * FailedIssuanceAttempts is status.failedIssuanceAttempts, which
     * cert-manager clears on success — so a non-zero value is a current fact.
     */
    "failedIssuanceAttempts": number;
}

/**
 * Cluster is a cluster as presented to the UI.
 */
export interface Cluster {
    /**
     * ID is the kubeconfig context name, and the handle every other call takes.
     */
    "id": string;

    /**
     * Server is the full API server URL.
     */
    "server": string;

    /**
     * Host is the host[:port] of the API server, for compact display.
     */
    "host": string;

    /**
     * DefaultNamespace is the namespace to preselect for this cluster.
     */
    "defaultNamespace": string;

    /**
     * AuthInfo names the kubeconfig user. Never a credential.
     */
    "authInfo": string;

    /**
     * IsCurrent marks the kubeconfig's current context.
     */
    "isCurrent": boolean;

    /**
     * IsReachable reports whether PodSteer has reached this cluster.
     */
    "isReachable": boolean;

    /**
     * Version is the API server's git version, empty until reached.
     */
    "version": string;

    /**
     * Platform is the API server's os/arch, empty until reached.
     */
    "platform": string;
}

/**
 * ClusterEvents is one cluster's share of a cross-cluster event list.
 */
export interface ClusterEvents {
    "cluster": string;
    "status": string;
    "reason": string;
    "missing": string[] | null;
    "events": Event[] | null;
}

/**
 * ClusterPods is one cluster's share of a cross-cluster pod list.
 */
export interface ClusterPods {
    /**
     * Cluster is the cluster the rows came from.
     */
    "cluster": string;

    /**
     * Status is the domain.ClusterReadStatus verdict on the read.
     */
    "status": string;

    /**
     * Reason is the operator-facing sentence for a status that is not ok or
     * slow — the same sentence a failed single-cluster call would have shown,
     * so the strip cannot say something the tab beside it would not.
     */
    "reason": string;

    /**
     * Missing names what a partial read did not get. Empty otherwise.
     */
    "missing": string[] | null;

    /**
     * Pods are the rows that arrived.
     */
    "pods": Pod[] | null;
}

/**
 * ClusterWorkloads is one cluster's share of a cross-cluster workload list.
 */
export interface ClusterWorkloads {
    "cluster": string;
    "status": string;
    "reason": string;
    "missing": string[] | null;
    "workloads": Workload[] | null;
}

/**
 * CodingAgentDTO is one coding agent found on the operator's machine.
 */
export interface CodingAgentDTO {
    /**
     * ID is the binary's name, and what StartAgentSession takes back.
     */
    "id": string;

    /**
     * Label is what the operator reads.
     */
    "label": string;

    /**
     * Path is where it was found, shown so it is obvious WHICH binary this is
     * — a machine can easily have two.
     */
    "path": string;
}

/**
 * ConditionCount is how many nodes are raising one condition.
 */
export interface ConditionCount {
    "condition": string;
    "nodes": number;
}

/**
 * ConditionRef is one status condition, for classification.
 */
export interface ConditionRef {
    "type": string;
    "status": string;

    /**
     * Phase is the subject's own phase, where it has one — a pod's.
     * 
     * The only context the classification takes, and it takes it because a
     * finished pod carries Ready=False and ContainersReady=False for ever,
     * correctly, so a rule reading type and status alone put two warnings on
     * the panel of every healthy completed Job. Empty for everything that has
     * no phase, which is most kinds.
     */
    "phase": string;
}

/**
 * Consumer is one pod's measured usage beside what it reserved.
 */
export interface Consumer {
    "namespace": string;
    "name": string;
    "node": string;

    /**
     * Usage and Request are pre-formatted for the dimension being ranked.
     */
    "usage": string;
    "request": string;

    /**
     * Share is usage over the reservation as a percentage, or -1 when nothing
     * was reserved — which is itself worth showing rather than hiding.
     */
    "share": number;

    /**
     * ShareLabel is that figure formatted, empty when nothing was reserved.
     */
    "shareLabel": string;

    /**
     * Percent is this pod's share of the whole list's largest, for the bar.
     */
    "percent": number;
}

/**
 * Consumption is what a set of pods is using, against what they reserved.
 * 
 * SHARED BY EVERY ROW THAT AGGREGATES PODS — a namespace and a controller —
 * so the two lists draw the same meter as the pod list, from the same fields,
 * with the same rules about what an absent denominator means. Three lists
 * each inventing their own shape is how three lists end up disagreeing about
 * what 85% is a percentage of.
 * 
 * Both formatted and raw. The strings are what a cell and a caption print;
 * the numbers are what a chart plots and what its reference lines sit at, and
 * they are carried separately because the formatted CPU is rounded to two
 * decimals — enough to read, and wrong to plot or to add up.
 */
export interface Consumption {
    /**
     * Pods is how many pods the figures cover, MeasuredPods how many of those
     * reported a measurement. Fewer measured than pods means the total is
     * real and short.
     */
    "pods": number;
    "measuredPods": number;

    /**
     * MeasurablePods is how many COULD be measured — the ones on a node.
     * metrics-server never reports a finished or unscheduled pod, so this is
     * the denominator for "is this total short", not Pods.
     */
    "measurablePods": number;

    /**
     * HasMetrics is whether there are figures to draw.
     */
    "hasMetrics": boolean;

    /**
     * MetricsAvailable is whether the CLUSTER serves metrics at all.
     * 
     * The UI must not collapse the two. An idle namespace on a metered
     * cluster and a cluster with no metrics-server both measure nothing, and
     * telling somebody to install one when they already have it is the bug
     * this field exists to prevent.
     */
    "metricsAvailable": boolean;

    /**
     * CPU and Memory are what the pods are using, formatted.
     */
    "cpu": string;
    "memory": string;

    /**
     * The reference figures, formatted.
     */
    "cpuRequest": string;
    "memoryRequest": string;
    "cpuLimit": string;
    "memoryLimit": string;

    /**
     * Whether there is a denominator at all. A zero percentage cannot stand
     * in for these: a set of pods that DID reserve CPU and is idle also reads
     * 0%, and the two must not draw the same thing.
     */
    "hasCpuRequest": boolean;
    "hasMemoryRequest": boolean;
    "hasCpuLimit": boolean;
    "hasMemoryLimit": boolean;

    /**
     * Usage as a percentage of the request, and of the limit. The first says
     * whether the reservation was right; only the second predicts throttling
     * or a kill.
     */
    "cpuPercent": number;
    "memoryPercent": number;
    "cpuLimitPercent": number;
    "memoryLimitPercent": number;

    /**
     * The same figures raw, for sorting a column and plotting a chart: CPU in
     * cores, memory in bytes.
     */
    "cpuCores": number;
    "memoryBytes": number;
    "requestCores": number;
    "requestBytes": number;
    "limitCores": number;
    "limitBytes": number;
}

/**
 * Container is a container as presented to the UI.
 */
export interface Container {
    /**
     * Name is the container name.
     */
    "name": string;

    /**
     * Image is the image reference actually running, when known.
     */
    "image": string;

    /**
     * Ready reports whether the container passes readiness.
     */
    "ready": boolean;

    /**
     * RestartCount is how many times the kubelet restarted it.
     */
    "restartCount": number;

    /**
     * State is "Waiting", "Running", "Terminated" or "Unknown".
     */
    "state": string;

    /**
     * Reason explains the state, e.g. "CrashLoopBackOff". May be empty.
     */
    "reason": string;

    /**
     * Started reports whether the startup probe has passed. Distinct from
     * Ready: started with not-ready is a readiness problem, not-started is a
     * startup problem, and they are looked into in different places.
     */
    "started": boolean;

    /**
     * TTY and Stdin quote the container's own spec: whether it allocates a
     * pseudo-terminal and keeps standard input open. Both must be true
     * before the terminal pane offers Attach (connecting to this container's
     * own running process) as an alternative to Shell (starting a new one).
     */
    "tty": boolean;
    "stdin": boolean;

    /**
     * Requests and Limits, formatted for display. Empty when undeclared.
     */
    "requests": string;
    "limits": string;

    /**
     * CPU and Memory are what THIS container is using, when anything measured
     * it — the half of a pod's total that says where the total came from. An
     * em dash when unmeasured, the same as the pod's own figures.
     */
    "cpu": string;
    "memory": string;
    "hasMetrics": boolean;

    /**
     * LastTermination explains how this container's previous life ended, and
     * is absent when it has not restarted. See domain.Termination: this is
     * the ONLY record of it Kubernetes keeps, and only of the most recent one.
     */
    "lastTermination"?: Termination | null;
}

/**
 * Credit is one shipped dependency, as the Credits pane shows it.
 */
export interface Credit {
    "name": string;
    "version": string;
    "ecosystem": string;
    "licence": string;
    "copyright": string;

    /**
     * TextID keys into the licence texts returned by LicenceText. Empty when
     * the project publishes no licence file.
     */
    "textId": string;

    /**
     * NoticeTextID keys into the same texts, for the NOTICE that Apache-2.0
     * section 4(d) requires to be reproduced alongside the licence.
     */
    "noticeTextId": string;

    /**
     * Expression is the original SPDX expression when a package offers a
     * choice and one arm was elected, so the pane never silently asserts one
     * licence for something dual-licensed.
     */
    "expression": string;
}

/**
 * DiskSummary is what the kubelets said about node filesystems.
 */
export interface DiskSummary {
    /**
     * Measured is how many nodes answered. Zero means the cluster did not
     * grant nodes/proxy, or no kubelet could be reached.
     */
    "measured": number;

    /**
     * Fullest is the highest occupancy across every node that answered, which
     * is the one that decides when eviction starts.
     */
    "fullestPercent": number;

    /**
     * FullestNode names it, so the figure can be acted on.
     */
    "fullestNode": string;

    /**
     * Filling counts nodes past the warning threshold.
     */
    "filling": number;
}

/**
 * DrainFailure is one pod a drain attempted and could not evict, or could not
 * confirm gone.
 */
export interface DrainFailure {
    "pod": string;
    "reason": string;
}

/**
 * DrainPlanDTO previews what a drain would do, without doing it — what
 * PlanDrain returns, over the wire.
 */
export interface DrainPlanDTO {
    /**
     * Evict names the pods the drain would evict.
     */
    "evict": string[] | null;

    /**
     * Skipped are pods the drain leaves alone regardless of options.
     */
    "skipped": DrainSkip[] | null;

    /**
     * Refused are pods that block the plan until an option changes.
     */
    "refused": DrainSkip[] | null;

    /**
     * Runnable is false the moment Refused is non-empty. The frontend
     * disables its confirm button on this rather than re-deriving it from
     * len(Refused), so the domain's own rule is the one place that decides.
     */
    "runnable": boolean;
}

/**
 * DrainReportDTO is what happened when a drain ran, whether or not it
 * finished cleanly — what DrainNode returns, over the wire.
 */
export interface DrainReportDTO {
    /**
     * Cordoned reports whether the node was marked unschedulable, true even
     * when everything after it failed.
     */
    "cordoned": boolean;

    /**
     * Evicted names the pods successfully evicted and confirmed gone.
     */
    "evicted": string[] | null;

    /**
     * Skipped mirrors the plan's own Skipped.
     */
    "skipped": DrainSkip[] | null;

    /**
     * Refused mirrors the plan's own Refused. Non-empty only when the drain
     * stopped before evicting anything.
     */
    "refused": DrainSkip[] | null;

    /**
     * Failed are pods the drain could not evict or could not confirm gone,
     * for a reason other than a timeout.
     */
    "failed": DrainFailure[] | null;

    /**
     * TimedOut reports whether the timeout was reached while still waiting
     * on a PodDisruptionBudget or a pod's termination.
     */
    "timedOut": boolean;
}

/**
 * DrainSkip is one pod a drain plan or report leaves alone, or refuses to
 * touch, and why. Reason is shown verbatim: domain.DrainReason values are
 * already written as sentences, not codes the frontend has to map.
 */
export interface DrainSkip {
    "pod": string;
    "reason": string;
}

/**
 * Event is a Kubernetes Event as presented to the UI.
 */
export interface Event {
    "name": string;
    "namespace": string;

    /**
     * Type is "Normal" or "Warning".
     */
    "type": string;
    "isWarning": boolean;
    "reason": string;
    "message": string;

    /**
     * InvolvedObject is the subject rendered as "Kind/name".
     */
    "involvedObject": string;
    "involvedKind": string;
    "involvedName": string;
    "source": string;
    "count": number;
    "firstSeen": string;
    "lastSeen": string;
    "ageSeconds": number;

    /**
     * Labels are the event object's own labels, almost always empty.
     */
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations are only the projected keys — see Pod.Annotations.
     */
    "annotations": { [_ in string]?: string } | null;
}

/**
 * Finding is one problem, aggregated across the objects it affects.
 */
export interface Finding {
    "id": string;

    /**
     * Severity is "critical", "warning" or "info".
     */
    "severity": string;

    /**
     * Category groups findings by what an operator would do about them.
     */
    "category": string;
    "title": string;
    "summary": string;

    /**
     * Advice says what to do about it, which is the half a raw Kubernetes
     * reason string never carries.
     */
    "advice": string;
    "subjects": Subject[] | null;
    "count": number;

    /**
     * KindID is the navigator target, so the UI can offer to open the list
     * the finding came from.
     */
    "kindId": string;

    /**
     * Truncated reports whether more objects are affected than are listed.
     */
    "truncated": boolean;
    "oldestSeconds": number;
}

/**
 * GraphEdge is a dependency, drawn the way a request travels.
 */
export interface GraphEdge {
    "from": string;
    "to": string;
    "label": string;
}

/**
 * GraphNode is one box on a pod's dependency map.
 */
export interface GraphNode {
    "id": string;

    /**
     * Kind is the map's own category — "ingress", "service", "workload",
     * "pod", "container" and so on. Not the Kubernetes kind: the map groups a
     * Deployment and a StatefulSet as one thing because a reader following a
     * request does not need them distinguished at that moment.
     */
    "kind": string;

    /**
     * APIKind is the Kubernetes kind, for the label and for following the node
     * into its own panel. Empty for containers, which are not objects.
     */
    "apiKind": string;
    "name": string;
    "namespace": string;

    /**
     * Tier is how far down the request path this sits, and drives the layout.
     */
    "tier": number;

    /**
     * Detail is a short qualifier — a port, an image tag, a host.
     */
    "detail": string;

    /**
     * Healthy is false for anything worth looking at. A map in one colour says
     * where things are; the colour says where to start.
     */
    "healthy": boolean;

    /**
     * Subject marks the object the map was opened from.
     */
    "subject": boolean;

    /**
     * Missing marks a reference resolved against the cluster and found to name
     * nothing. Distinct from an unhealthy node: an unwell object exists and is
     * failing, a missing one was named by something and is not there, and the
     * two call for opposite next steps.
     */
    "missing": boolean;

    /**
     * Group names the node whose children this is one of, for folding a
     * sibling set. Empty for anything with no natural set. The graph is always
     * complete — what is drawn is the view's decision.
     */
    "group": string;
}

/**
 * HistorySettings is what PodSteer records, and how often.
 */
export interface HistorySettings {
    /**
     * RetentionDays is 0 when nothing is recorded.
     */
    "retentionDays": number;

    /**
     * MaxDays is the ceiling the UI should offer.
     */
    "maxDays": number;

    /**
     * IntervalSeconds is the sampling cadence.
     */
    "intervalSeconds": number;

    /**
     * The bounds the cadence is clamped to, so the UI never offers a value
     * the backend would silently change.
     */
    "minIntervalSeconds": number;
    "maxIntervalSeconds": number;
}

/**
 * ImageReport is what Kubernetes reports about one container's image.
 */
export interface ImageReport {
    "container": string;

    /**
     * Declared is spec.containers[].image; Resolved is what the kubelet says
     * it is running. Drift reports that they differ.
     */
    "declared": string;
    "resolved": string;
    "drift": boolean;

    /**
     * Registry, Repository and Tag are the resolved reference parsed, with a
     * runtime's own defaults applied. Empty when it could not be parsed,
     * which ReferenceReadable reports.
     */
    "registry": string;
    "repository": string;
    "tag": string;
    "referenceReadable": boolean;

    /**
     * Digest is the content digest Kubernetes reported for what is running.
     */
    "digest": string;

    /**
     * DigestNote explains a node and a container status that disagree about
     * it, which is what a multi-platform image looks like.
     */
    "digestNote": string;

    /**
     * SizeBytes and SizeStatus are the image's size on the node that pulled
     * it. READ SizeStatus FIRST: "measured", "not_reported" or "unreadable",
     * and SizeBytes is zero for the last two — a dash, never a nought.
     */
    "sizeBytes": number;
    "sizeStatus": string;

    /**
     * SizeSource names whose number it is, or why there is none.
     */
    "sizeSource": string;

    /**
     * OtherNames are the other references the node knows the same image by.
     */
    "otherNames": string[] | null;

    /**
     * PullPolicy and PullSecrets quote the pod's spec. The Secrets are NAMES
     * only and nothing on this path reads their contents.
     */
    "pullPolicy": string;
    "pullSecrets": string[] | null;

    /**
     * Credentialed reports that the pull used a Secret, so the panel can say
     * what it did not look at.
     */
    "credentialed": boolean;

    /**
     * CredentialNote is the sentence for that case.
     */
    "credentialNote": string;

    /**
     * Bounded is the line saying what is NOT here and why — the layers, the
     * entrypoint, the labels. Always set, and the panel always shows it:
     * empty space where layers would be is a claim nothing checked.
     */
    "bounded": string;
}

/**
 * KubeStateMetrics is a kube-state-metrics installation found in the cluster.
 * 
 * No proxy target and no query surface, deliberately — see
 * domain.KubeStateMetrics. What crosses the bridge is what a person needs to
 * go and look at it.
 */
export interface KubeStateMetrics {
    /**
     * Found reports whether anything was discovered. A boolean rather than
     * leaving the frontend to test Service for emptiness, so "is it there"
     * is answered by the same rule on both sides of the bridge.
     */
    "found": boolean;

    /**
     * Label is what to show a person, e.g. "kube-state-metrics in monitoring".
     */
    "label": string;
    "namespace": string;
    "service": string;

    /**
     * Port may be empty: a service whose metrics port this build does not
     * recognise is still kube-state-metrics, and nothing here connects to it.
     */
    "port": string;
}

/**
 * KubeconfigMerge is what adding a kubeconfig would change, or did.
 */
export interface KubeconfigMerge {
    /**
     * Added names the contexts that would be, or were, added.
     */
    "added": string[] | null;

    /**
     * Conflicts names contexts the kubeconfig already defines. A merge with
     * any of these is refused.
     */
    "conflicts": string[] | null;

    /**
     * Path is the file that was, or would be, written.
     */
    "path": string;
}

/**
 * LocalShellSupportDTO reports whether this platform can open a local shell.
 */
export interface LocalShellSupportDTO {
    /**
     * Supported is false on Windows, where there is no pseudo-terminal here.
     */
    "supported": boolean;

    /**
     * Reason is the sentence to show when it is not, empty when it is.
     */
    "reason": string;
}

/**
 * MetricsBackend is a monitoring system found running in the cluster.
 */
export interface MetricsBackend {
    /**
     * Kind is "prometheus", or empty when nothing was found.
     */
    "kind": string;

    /**
     * Label is what to show a person, e.g. "Prometheus in monitoring".
     */
    "label": string;
    "namespace": string;
    "service": string;
    "port": string;
}

/**
 * Namespace is a namespace as presented to the UI.
 */
export interface Namespace {
    /**
     * Name is the namespace name.
     */
    "name": string;

    /**
     * Phase is the lifecycle phase, e.g. "Active" or "Terminating".
     */
    "phase": string;

    /**
     * IsActive reports whether the namespace accepts new objects.
     */
    "isActive": boolean;

    /**
     * Labels are the namespace's labels.
     */
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations are only the projected keys — see Pod.Annotations.
     */
    "annotations": { [_ in string]?: string } | null;

    /**
     * CreatedAt is the creation timestamp in RFC 3339, empty if unknown.
     */
    "createdAt": string;

    /**
     * AgeSeconds is the age at the time of the call.
     */
    "ageSeconds": number;
}

/**
 * NamespaceInventory is what a namespace holds, as presented to the UI.
 */
export interface NamespaceInventory {
    "namespace": string;

    /**
     * Counts holds the kinds that hold something, largest first, followed by
     * any that could not be read.
     */
    "counts": ResourceCount[] | null;

    /**
     * Empty is how many kinds were counted and hold nothing.
     */
    "empty": number;

    /**
     * Total is the sum of the known counts — of the built-in kinds only. The
     * UI says so; custom resources are not counted.
     */
    "total": number;

    /**
     * Unreadable is how many kinds were refused.
     */
    "unreadable": number;
}

/**
 * NamespaceLoad is one namespace's share of the cluster.
 */
export interface NamespaceLoad {
    "name": string;
    "pods": number;
    "notReady": number;

    /**
     * Formatted for display, plus the percentages the bars need.
     */
    "cpuRequests": string;
    "memoryRequests": string;
    "cpuUsage": string;
    "memoryUsage": string;
    "cpuShare": number;
    "memoryShare": number;
    "measured": boolean;
}

/**
 * NamespaceSummary is a namespace with what is running in it.
 */
export interface NamespaceSummary {
    /**
     * Name is the namespace name.
     */
    "name": string;

    /**
     * Phase is the lifecycle phase, e.g. "Active" or "Terminating".
     */
    "phase": string;

    /**
     * IsActive reports whether the namespace accepts new objects.
     */
    "isActive": boolean;

    /**
     * Labels are the namespace's labels.
     */
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations are only the projected keys — see Pod.Annotations.
     */
    "annotations": { [_ in string]?: string } | null;

    /**
     * CreatedAt is the creation timestamp in RFC 3339, empty if unknown.
     */
    "createdAt": string;

    /**
     * AgeSeconds is the age at the time of the call.
     */
    "ageSeconds": number;

    /**
     * NotReady is how many of its pods are not doing their job.
     */
    "notReady": number;

    /**
     * Pods is how many pods the figures cover, MeasuredPods how many of those
     * reported a measurement. Fewer measured than pods means the total is
     * real and short.
     */
    "pods": number;
    "measuredPods": number;

    /**
     * MeasurablePods is how many COULD be measured — the ones on a node.
     * metrics-server never reports a finished or unscheduled pod, so this is
     * the denominator for "is this total short", not Pods.
     */
    "measurablePods": number;

    /**
     * HasMetrics is whether there are figures to draw.
     */
    "hasMetrics": boolean;

    /**
     * MetricsAvailable is whether the CLUSTER serves metrics at all.
     * 
     * The UI must not collapse the two. An idle namespace on a metered
     * cluster and a cluster with no metrics-server both measure nothing, and
     * telling somebody to install one when they already have it is the bug
     * this field exists to prevent.
     */
    "metricsAvailable": boolean;

    /**
     * CPU and Memory are what the pods are using, formatted.
     */
    "cpu": string;
    "memory": string;

    /**
     * The reference figures, formatted.
     */
    "cpuRequest": string;
    "memoryRequest": string;
    "cpuLimit": string;
    "memoryLimit": string;

    /**
     * Whether there is a denominator at all. A zero percentage cannot stand
     * in for these: a set of pods that DID reserve CPU and is idle also reads
     * 0%, and the two must not draw the same thing.
     */
    "hasCpuRequest": boolean;
    "hasMemoryRequest": boolean;
    "hasCpuLimit": boolean;
    "hasMemoryLimit": boolean;

    /**
     * Usage as a percentage of the request, and of the limit. The first says
     * whether the reservation was right; only the second predicts throttling
     * or a kill.
     */
    "cpuPercent": number;
    "memoryPercent": number;
    "cpuLimitPercent": number;
    "memoryLimitPercent": number;

    /**
     * The same figures raw, for sorting a column and plotting a chart: CPU in
     * cores, memory in bytes.
     */
    "cpuCores": number;
    "memoryBytes": number;
    "requestCores": number;
    "requestBytes": number;
    "limitCores": number;
    "limitBytes": number;
}

/**
 * Node is a cluster node as presented to the UI.
 */
export interface Node {
    "name": string;

    /**
     * Status is the single word to show: Ready, NotReady, SchedulingDisabled
     * or the name of whichever pressure condition is firing.
     */
    "status": string;

    /**
     * Roles are the node's roles, e.g. ["control-plane"].
     */
    "roles": string[] | null;

    /**
     * IsControlPlane lets the UI mark control-plane nodes without re-parsing
     * the roles.
     */
    "isControlPlane": boolean;
    "isHealthy": boolean;
    "unschedulable": boolean;
    "taints": number;

    /**
     * CPU is usage in cores, formatted as the pod table shows it.
     */
    "cpu": string;

    /**
     * CPUPercent is usage against allocatable, for the meter.
     */
    "cpuPercent": number;
    "memory": string;

    /**
     * MemoryPercent is usage against allocatable.
     */
    "memoryPercent": number;

    /**
     * HasMetrics distinguishes "measured zero" from "no metrics-server", so
     * the UI can show a dash rather than a misleading 0%.
     */
    "hasMetrics": boolean;
    "version": string;
    "osImage": string;
    "architecture": string;
    "internalIp": string;
    "allocatableCpu": string;
    "allocatableMemory": string;

    /**
     * Disk is the FULLEST of the node's filesystems — whichever of nodefs and
     * imagefs is closer to full, because that is the one that decides whether
     * the kubelet starts evicting. Reporting the average, or only nodefs,
     * would hide a full image filesystem on a node that shares neither.
     * Disk is what is USED, alone, so the column renders the same shape as
     * CPU and memory: a value, a bar, a percentage. It carried "6.2GiB of
     * 40.0GiB" before, which needed a value box twice the width of its
     * neighbours and made one column of three look like a different kind of
     * thing. The capacity moved to DiskCapacity and is named in the tooltip.
     */
    "disk": string;

    /**
     * DiskCapacity is the size of that same filesystem, for the tooltip.
     */
    "diskCapacity": string;
    "diskPercent": number;

    /**
     * HasDisk distinguishes a node that reported an empty disk from one never
     * asked. Disk occupancy needs nodes/proxy, which plenty of clusters do
     * not grant, so absent is the ordinary case rather than a fault.
     */
    "hasDisk": boolean;
    "maxPods": number;

    /**
     * Labels are the node's labels.
     */
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations are only the projected keys — see Pod.Annotations.
     */
    "annotations": { [_ in string]?: string } | null;
    "createdAt": string;
    "ageSeconds": number;
}

/**
 * NodeLoad is one node's share of the work.
 */
export interface NodeLoad {
    "name": string;
    "ready": boolean;
    "schedulable": boolean;
    "controlPlane": boolean;

    /**
     * Reserved reports a node whose taint refuses untolerated pods. Its
     * shares are still its own; this is what stops them being read as
     * headroom anybody can use.
     */
    "reserved": boolean;

    /**
     * The shares drive the bars and the threshold colours.
     */
    "cpuPercent": number;
    "memoryPercent": number;
    "podPercent": number;

    /**
     * DiskPercent is -1 when no kubelet answered for this node.
     */
    "diskPercent": number;
    "pods": number;

    /**
     * What the node is CONSUMING, as opposed to every share above, which is
     * what pods reserved. Raw rather than formatted because the only consumer
     * is the usage chart, which needs numbers to plot.
     * 
     * UsageMeasured distinguishes a genuinely idle node from one no metrics
     * API answered for; without it a cluster with no metrics-server would
     * chart a confident flat zero.
     */
    "usageCpuMilli": number;
    "usageMemoryBytes": number;
    "usageMeasured": boolean;

    /**
     * The amounts and the shares, formatted here rather than by the browser,
     * so a node's row reads the same way a capacity track does: the quantity,
     * then what proportion of the node it is.
     */
    "cpuAmount": string;
    "memoryAmount": string;
    "podAmount": string;
    "diskAmount": string;
    "cpuShare": string;
    "memoryShare": string;
    "podShare": string;
    "diskShare": string;
    "diskMeasured": boolean;
}

/**
 * NodeShell is one live node shell, as the activity list shows it.
 */
export interface NodeShell {
    "id": string;
    "clusterId": string;
    "namespace": string;
    "pod": string;
    "node": string;
    "image": string;
}

/**
 * NodeSummary counts nodes by condition.
 */
export interface NodeSummary {
    "total": number;
    "ready": number;
    "notReady": number;
    "cordoned": number;
    "underPressure": number;
    "controlPlane": number;

    /**
     * Schedulable counts nodes an ordinary pod could be placed on, and
     * Tainted those that refuse one without a toleration.
     */
    "schedulable": number;
    "tainted": number;

    /**
     * Pressure counts nodes per condition raised, most affected first.
     */
    "pressure": ConditionCount[] | null;

    /**
     * Disks summarises node filesystem occupancy, when kubelets answered.
     */
    "disks": DiskSummary;

    /**
     * KubeletVersions counts nodes per version, most common first.
     */
    "kubeletVersions": VersionCount[] | null;
    "oldestSeconds": number;
}

/**
 * NotificationCapability is what the platform will actually do.
 * 
 * THE TWO HALVES ARE SEPARATE, and collapsing them would be the mistake this
 * codebase refuses to make elsewhere (MetricsStatus, ClusterReadStatus,
 * PodGraph.Bounded): "this build cannot show notifications at all" and "the
 * operator has denied this application permission" call for opposite
 * sentences — one is a fact about the platform that no setting changes, and
 * the other is fixed in the operating system's own preferences.
 */
export interface NotificationCapability {
    /**
     * Supported reports whether this build and platform can deliver at all.
     */
    "supported": boolean;

    /**
     * Authorised reports whether the operating system will let this
     * application post one. On platforms with no notion of it, true.
     */
    "authorised": boolean;
}

/**
 * NotificationRequest is one desktop notification, as the frontend asks for it.
 * 
 * EVERY FIELD HERE IS CHOSEN SO THAT NO OBJECT NAME CAN TRAVEL, and that is a
 * stricter rule than it looks. A desktop notification is not ephemeral: macOS
 * keeps delivered notifications in Notification Centre, which is a database on
 * disk, and a Linux notification daemon may log what it showed. So the same
 * no-object-names commitment SECURITY.md makes about files applies here in
 * full — a notification is a write.
 * 
 * What that buys is that the fields are deliberately few. Title and Body carry
 * a finding's TITLE, which is a rule's own name ("CrashLoopBackOff") written
 * in this repository, and a count. There is no field for a namespace, a pod,
 * a node or a workload, and adding one is the change this comment exists to
 * make somebody argue for — notification_api_test.go asserts the field set
 * against a literal list for exactly that reason, the way
 * settingsFile.test.ts does for the export.
 * 
 * ClusterID is a kubeconfig CONTEXT NAME. It is the one cluster-shaped thing
 * that travels, on the same terms the settings file lets it travel: it is a
 * handle the operator's own machine already gives them and it identifies
 * nothing inside any cluster.
 */
export interface NotificationRequest {
    /**
     * ID identifies this notification to the OS, so a later one can replace
     * it rather than stacking beside it.
     */
    "id": string;

    /**
     * Title is the headline.
     */
    "title": string;

    /**
     * Body is the sentence under it. May be empty.
     */
    "body": string;

    /**
     * ClusterID is the tab to bring forward when the notification is clicked.
     */
    "clusterId": string;
}

/**
 * Overview is the assessed state of one cluster.
 */
export interface Overview {
    "clusterId": string;
    "version": string;
    "platform": string;

    /**
     * Health is "healthy", "degraded" or "critical".
     */
    "health": string;
    "generatedAt": string;
    "findings": Finding[] | null;
    "capacity": CapacitySummary;
    "nodes": NodeSummary;
    "storage": StorageSummary;
    "consumers": TopConsumers;
    "support": ReleaseSupport;
    "nodeLoads": NodeLoad[] | null;
    "pods": PodSummary;
    "workloads": WorkloadKindSummary[] | null;
    "namespaces": NamespaceLoad[] | null;
    "restarts": RestartHotspot[] | null;

    /**
     * Unavailable names data sources that could not be read, so the UI can
     * say "no metrics" instead of quietly showing zeroes.
     */
    "unavailable": string[] | null;

    /**
     * Metrics says why usage figures are absent, when they are: "measured",
     * "not-installed", "forbidden" or "failed". The UI needs the distinction
     * because "install metrics-server" is the wrong advice for somebody who
     * is merely not allowed to read the one already running.
     */
    "metrics": string;

    /**
     * Backend names a monitoring system already running in this cluster, when
     * one was found — empty otherwise, which is the ordinary case.
     * 
     * It changes nothing PodSteer measures. It is here so the UI can point at
     * a system that already keeps months of the same figures PodSteer keeps
     * minutes of, instead of presenting its own window as the whole picture.
     */
    "backend": MetricsBackend;

    /**
     * KubeState names a kube-state-metrics installation found in this
     * cluster, when one was found — empty otherwise, which is the ordinary
     * case.
     * 
     * It changes nothing PodSteer measures either, and unlike Backend it is
     * not even a candidate for being read: it is a scrape endpoint, and the
     * note built on it says in as many words that the figures on this screen
     * come from the metrics API and from PodSteer's own samples instead.
     */
    "kubeState": KubeStateMetrics;

    /**
     * Counts the findings by severity, so the header does not have to.
     */
    "criticalCount": number;
    "warningCount": number;
    "infoCount": number;

    /**
     * Upgrade summarises the upgrade-impact findings against Support.Minor's
     * next release, or whatever minor the "check against" selector chose —
     * see GetOverviewForTarget.
     */
    "upgrade": UpgradeSummary;

    /**
     * KnownMinors is every minor the support-window table has an entry for,
     * oldest first — what the "check against" selector offers, bounded to
     * versions this build can actually reason about instead of a free-text
     * field that could ask about one neither table has heard of.
     */
    "knownMinors": string[] | null;
}

/**
 * PhaseCount is how many objects are in one phase.
 */
export interface PhaseCount {
    "phase": string;
    "count": number;
}

/**
 * Pod is a pod as presented to the UI.
 * 
 * Several fields are derived rather than raw — Ready, Restarts, StatusReason,
 * IsHealthy — because the derivation is domain logic. Computing them in Go
 * once keeps a single definition of "healthy" in the codebase instead of
 * letting a second, subtly different one grow in the frontend.
 */
export interface Pod {
    /**
     * UID is the Kubernetes object UID. May be empty.
     */
    "uid": string;

    /**
     * Name is the pod name.
     */
    "name": string;

    /**
     * Namespace is the pod's namespace.
     */
    "namespace": string;

    /**
     * ClusterID is the cluster the pod was read from.
     */
    "clusterId": string;

    /**
     * Phase is the lifecycle phase, including the derived "Terminating".
     */
    "phase": string;

    /**
     * StatusReason explains an unhealthy pod, e.g. "ImagePullBackOff".
     * Empty when nothing is wrong.
     */
    "statusReason": string;

    /**
     * NodeName is the node running the pod, empty while unscheduled.
     */
    "nodeName": string;

    /**
     * PodIP is the pod's cluster IP, empty before assignment.
     */
    "podIp": string;

    /**
     * Ready is the ready/total container count formatted for display, "2/3".
     */
    "ready": string;

    /**
     * ReadyContainers is how many containers pass readiness.
     */
    "readyContainers": number;

    /**
     * TotalContainers is how many containers the pod declares.
     */
    "totalContainers": number;

    /**
     * Restarts is the pod's total restart count.
     */
    "restarts": number;

    /**
     * IsHealthy reports whether the pod is doing what it should.
     */
    "isHealthy": boolean;

    /**
     * ControlledBy names the controlling owner as "Kind/name". Empty for a
     * bare pod, which is itself worth knowing: nothing will recreate it.
     */
    "controlledBy": string;

    /**
     * QoSClass is Guaranteed, Burstable or BestEffort — the eviction order
     * under node pressure.
     */
    "qosClass": string;

    /**
     * CPU is measured usage in cores, or an em dash when unmeasured.
     */
    "cpu": string;

    /**
     * Memory is measured working-set memory, or an em dash.
     */
    "memory": string;

    /**
     * HasMetrics distinguishes a measured zero from no metrics-server.
     */
    "hasMetrics": boolean;

    /**
     * CPUPercent and MemoryPercent are usage against what the pod REQUESTED,
     * for the meters — a node's meters divide by allocatable, which a pod has
     * no equivalent of. They may exceed 100: a request is a reservation, not
     * a ceiling. See domain.Pod.CPUPercent.
     */
    "cpuPercent": number;
    "memoryPercent": number;

    /**
     * CPURequest and MemoryRequest are the reservation itself, formatted, so
     * a meter can name the number it is a proportion OF instead of leaving a
     * bare percentage to be taken on trust.
     */
    "cpuRequest": string;
    "memoryRequest": string;

    /**
     * HasCPURequest and HasMemoryRequest say whether there is a denominator
     * at all. Separate flags because the two are declared independently: a
     * pod may reserve memory and leave CPU unbounded, which is a common and
     * deliberate shape rather than an oversight.
     * 
     * A zero percentage cannot stand in for these. An idle pod that DID
     * reserve CPU also reads 0%, and the two must not draw the same thing.
     */
    "hasCpuRequest": boolean;
    "hasMemoryRequest": boolean;

    /**
     * The same four figures against the pod's LIMITS, which is a different
     * question: the request is what it reserved, the limit is what it will be
     * stopped at. Only this one can predict a failure — see
     * domain.Pod.MemoryLimitPercent, and note that its CPU twin predicts
     * throttling rather than death.
     */
    "cpuLimitPercent": number;
    "memoryLimitPercent": number;
    "cpuLimit": string;
    "memoryLimit": string;
    "hasCpuLimit": boolean;
    "hasMemoryLimit": boolean;

    /**
     * Containers are the pod's containers.
     */
    "containers": Container[] | null;

    /**
     * Findings are what is wrong with this pod, or about to be — each with
     * what to do about it. See domain.AssessPod. Empty for a pod with nothing
     * worth saying about it, which is most of them.
     */
    "findings": PodFinding[] | null;

    /**
     * Labels are the pod's labels.
     */
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations are ONLY the keys the list was asked for — the custom
     * columns' — never the whole map. See domain.Projection.
     */
    "annotations": { [_ in string]?: string } | null;

    /**
     * CreatedAt is the creation timestamp in RFC 3339, empty if unknown.
     */
    "createdAt": string;

    /**
     * AgeSeconds is the age at the time of the call.
     */
    "ageSeconds": number;
}

/**
 * PodCapacity is how many pods the cluster runs against how many it can.
 * Every count arrives pre-formatted alongside its raw value: the strings are
 * what the card prints, and the numbers are what it makes decisions with —
 * whether to colour a figure, whether to show a row at all. The frontend does
 * no arithmetic on any of it, so the rounding somebody reads here is the same
 * rounding the Go tests assert.
 */
export interface PodCapacity {
    "scheduled": number;
    "scheduledLabel": string;
    "healthy": number;
    "healthyLabel": string;
    "capacity": number;
    "capacityLabel": string;

    /**
     * Free is the slots nothing occupies.
     */
    "free": number;
    "freeLabel": string;

    /**
     * Reserved is slots on tainted nodes, which only a pod that tolerates
     * them can use. Zero on most clusters, most of the machine on some.
     */
    "reserved": number;
    "reservedLabel": string;

    /**
     * ReservedNodes is how many nodes hold them, for the sentence that
     * explains the difference between the two figures.
     */
    "reservedNodes": number;
    "unschedulable": number;
    "unschedulableLabel": string;

    /**
     * The shares, already rounded, as strings ending in a per-cent sign.
     */
    "usedPercent": string;
    "freePercent": string;
    "healthyPercent": string;
    "waitingPercent": string;

    /**
     * UsedPercentValue drives the bar and the threshold colour.
     */
    "usedPercentValue": number;
}

/**
 * PodFinding is one thing worth telling an operator about a pod.
 */
export interface PodFinding {
    "severity": string;
    "title": string;
    "detail": string;
    "advice": string;
}

/**
 * PodGraph is the dependency chain around one pod.
 */
export interface PodGraph {
    "nodes": GraphNode[] | null;
    "edges": GraphEdge[] | null;

    /**
     * Unreadable names sources that could not be read, so the map can say it
     * is incomplete rather than implying nothing is there.
     */
    "unreadable": string[] | null;

    /**
     * Bounded is one short line saying why nothing is drawn below the subject,
     * on a map whose subject has no cheap downward answer. Empty on a pod or
     * workload map. Not the same fact as Unreadable: that means a read was
     * refused, this means none was attempted.
     */
    "bounded": string;
}

/**
 * PodSummary counts pods by the state an operator cares about.
 */
export interface PodSummary {
    "total": number;
    "running": number;
    "pending": number;
    "succeeded": number;
    "failed": number;
    "terminating": number;
    "unknown": number;
    "notReady": number;
    "restarts": number;
    "bestEffort": number;
}

/**
 * PolicyRule is one RBAC rule, as the cluster stated it.
 */
export interface PolicyRule {
    /**
     * Verbs are the actions permitted. "*" is all of them.
     */
    "verbs": string[] | null;

    /**
     * APIGroups are the groups the resources live in. "" is the core group.
     */
    "apiGroups": string[] | null;

    /**
     * Resources are the resource plurals, optionally "resource/subresource".
     */
    "resources": string[] | null;

    /**
     * ResourceNames narrows the rule to named objects, and is usually empty.
     */
    "resourceNames": string[] | null;

    /**
     * NonResourceURLs are URL paths, which belong to the API server rather
     * than to any namespace.
     */
    "nonResourceUrls": string[] | null;
}

/**
 * PortForward is one live forward, as the UI shows it.
 */
export interface PortForward {
    "id": string;
    "clusterId": string;
    "namespace": string;
    "pod": string;
    "localPort": number;
    "remotePort": number;

    /**
     * Address is where to point a browser, scheme included.
     */
    "address": string;

    /**
     * Scheme is "http" or "https", guessed from the container port's name —
     * see domain.SchemeForPort. Carried separately from Address, which is
     * meant for display against "localhost", so the frontend can build the
     * 127.0.0.1 form OpenURL needs without re-parsing a string built for
     * something else.
     */
    "scheme": string;

    /**
     * Reconnecting reports that the pod behind this forward went away and a
     * replacement is being sought. The local port stays bound throughout, so
     * whatever is pointed at it keeps its address and simply stalls.
     */
    "reconnecting": boolean;
}

/**
 * ProbeResult is a finished reachability probe.
 */
export interface ProbeResult {
    /**
     * Vantage is "local" or "in_cluster" — WHERE the answer is true of, and
     * the panel is expected to say it.
     */
    "vantage": string;

    /**
     * Route is "service_proxy", "port_forward" or "exec": how the vantage
     * reached the target, which decides what a success is evidence of.
     */
    "route": string;

    /**
     * Target is host:port as it was actually addressed.
     */
    "target": string;

    /**
     * Scheme is "http", "https" or "" when the probe was a bare TCP connect.
     */
    "scheme": string;

    /**
     * Outcome is "reachable", "name_not_resolved", "refused" or "unknown".
     */
    "outcome": string;

    /**
     * Summary is one sentence naming the vantage, the target and the outcome.
     */
    "summary": string;

    /**
     * Steps are what the probe did, in order.
     */
    "steps": ProbeStep[] | null;

    /**
     * StatusCode is the HTTP status, or 0 when no request was made.
     */
    "statusCode": number;

    /**
     * ElapsedMs is wall time for the whole probe.
     */
    "elapsedMs": number;

    /**
     * TimeoutMs is the ceiling that applied, so the panel can say what it is
     * rather than implying the wait was unbounded.
     */
    "timeoutMs": number;
}

/**
 * ProbeStep is one step of a probe and what it produced.
 * 
 * DNS and connect are separate steps on the wire as well as in the domain,
 * because the panel has to be able to say which of them failed. A single
 * boolean would have been smaller and would have thrown away the only thing
 * that decides where an operator looks next.
 */
export interface ProbeStep {
    /**
     * Name is "dns", "connect" or "http".
     */
    "name": string;

    /**
     * Status is "ok", "failed" or "skipped". Skipped is not a failure: an
     * address literal has nothing to resolve.
     */
    "status": string;

    /**
     * Detail is what happened, in the words of whatever performed it.
     */
    "detail": string;
}

/**
 * ProbeSubjectInput is what the frontend read off the object it is offering
 * to probe. Every field is a quotation of the manifest already on screen, so
 * planning a probe costs no read at all.
 */
export interface ProbeSubjectInput {
    /**
     * Kind is the Kubernetes Kind verbatim: "Service", "Pod" or "Ingress".
     * Verbatim matters for the same reason a followable graph node's does —
     * a lowercased plural matches nothing and the probe silently refuses.
     */
    "kind": string;
    "namespace": string;
    "name": string;
    "serviceType": string;
    "clusterIp": string;
    "podIp": string;
    "host": string;
    "port": number;
    "portName": string;
    "protocol": string;
    "tls": boolean;
}

/**
 * RBACFinding is one blast-radius flag.
 */
export interface RBACFinding {
    /**
     * ID is stable for the same flag across inspections.
     */
    "id": string;

    /**
     * Severity is critical, warning or info.
     */
    "severity": string;

    /**
     * Title is the power granted, in a few words.
     */
    "title": string;

    /**
     * Detail says what it permits, in one sentence.
     */
    "detail": string;

    /**
     * Advice says why it matters.
     */
    "advice": string;
}

/**
 * RBACSubject is one account a binding names, or one being asked about.
 * 
 * A subject NAME IS AN OBJECT NAME: it crosses this boundary and is shown,
 * and it is never written to disk — the same commitment SECURITY.md makes
 * about every other object name.
 */
export interface RBACSubject {
    /**
     * Kind is "User", "Group" or "ServiceAccount". Empty means the current
     * account, which is what sends a review to the self API instead.
     */
    "kind": string;

    /**
     * Name is the account name.
     */
    "name": string;

    /**
     * Namespace is the ServiceAccount's namespace, and empty for the others.
     */
    "namespace": string;
}

/**
 * ReleaseSupport is what is known about the version the cluster runs.
 */
export interface ReleaseSupport {
    "minor": string;

    /**
     * State is unknown, supported, ending or ended. Unknown means the table
     * does not cover this release, not that anything is wrong with it.
     */
    "state": string;

    /**
     * EndOfLife is formatted for display, empty when nothing is claimed.
     */
    "endOfLife": string;

    /**
     * Days until that date, negative once it has passed.
     */
    "days": number;

    /**
     * CompiledAt is when the support table was generated, so an "unknown"
     * verdict can say it is an old table rather than a broken one.
     */
    "compiledAt": string;
}

/**
 * ResourceCount is how many objects of one kind a namespace holds.
 */
export interface ResourceCount {
    /**
     * KindID is the navigator handle, so the UI can open the list this
     * counted without looking a kind up by name.
     */
    "kindId": string;

    /**
     * Kind is the CamelCase singular, e.g. "ConfigMap".
     */
    "kind": string;

    /**
     * Title is the plural display name, e.g. "ConfigMaps".
     */
    "title": string;

    /**
     * Count is how many exist. Meaningless when Unreadable is set.
     */
    "count": number;

    /**
     * Unreadable says, shortly, why the count is unknown.
     * 
     * The UI must render this instead of the number rather than beside it: an
     * unknown count shown as 0 tells somebody a namespace is empty when it
     * may be full.
     */
    "unreadable": string;
}

/**
 * ResourceKind is a browsable kind, as presented to the navigator.
 */
export interface ResourceKind {
    /**
     * ID is the handle every list call takes back, "group/version/resource".
     */
    "id": string;

    /**
     * Group is the API group, empty for the core group.
     */
    "group": string;

    /**
     * Version is the API version.
     */
    "version": string;

    /**
     * Kind is the CamelCase singular, e.g. "Deployment".
     */
    "kind": string;

    /**
     * Namespaced reports whether objects live in a namespace. The UI hides
     * the namespace filter and column when false.
     */
    "namespaced": boolean;

    /**
     * Category places the kind in a navigator section.
     */
    "category": string;

    /**
     * Subcategory groups it within that section — the project publishing its
     * API group, for a custom resource, and empty for everything else.
     */
    "subcategory": string;

    /**
     * Title is the plural display name.
     */
    "title": string;

    /**
     * Singular is the singular display name.
     */
    "singular": string;

    /**
     * Rich reports whether PodSteer has purpose-built columns for this kind.
     * The UI routes rich kinds to their own view and everything else to the
     * generic table.
     */
    "rich": boolean;
}

/**
 * ResourceTable is a generically browsed kind, rendered with the columns the
 * API server itself prints.
 */
export interface ResourceTable {
    /**
     * KindID identifies what the table describes.
     */
    "kindId": string;

    /**
     * Title is the plural display name of the kind.
     */
    "title": string;

    /**
     * Namespaced reports whether the rows carry namespaces.
     */
    "namespaced": boolean;
    "columns": TableColumn[] | null;
    "rows": TableRow[] | null;
}

/**
 * ResourceUsage is one dimension of cluster capacity.
 */
export interface ResourceUsage {
    /**
     * Allocatable, Requests, Limits and Usage are pre-formatted for display.
     */
    "allocatable": string;
    "requests": string;
    "limits": string;
    "usage": string;

    /**
     * Schedulable is the allocatable amount not already requested — the
     * headroom a new pod can actually claim.
     */
    "schedulable": string;

    /**
     * PodUsage is what the pods alone consume, which is the half of the
     * efficiency ratio that Usage — measured across whole nodes — is not.
     */
    "podUsage": string;

    /**
     * The percentages drive the bars, so they are sent as numbers.
     */
    "requestPercent": number;
    "limitPercent": number;
    "usagePercent": number;

    /**
     * SchedulablePercent is the headroom as a share of allocatable, so every
     * figure on the card can show its amount and its proportion.
     */
    "schedulablePercent": number;

    /**
     * The same four shares, rounded and rendered here rather than by the
     * browser. The card prints these; the numbers above drive the bar and the
     * threshold colours.
     */
    "requestPercentLabel": string;
    "usagePercentLabel": string;
    "schedulablePercentLabel": string;
    "efficiencyLabel": string;

    /**
     * Efficiency is usage as a percentage of requests, or -1 when nothing was
     * measured. It is the number that says how much of the reservation is
     * actually being used.
     */
    "efficiency": number;

    /**
     * Measured distinguishes "measured zero" from "no metrics-server".
     */
    "measured": boolean;

    /**
     * Reported says whether the cluster published any capacity for this
     * dimension at all.
     * 
     * The amounts above are pre-formatted for display, so the frontend cannot
     * tell "0" from "not published" by looking at them — and the difference
     * matters for ephemeral storage, which some providers do not report.
     * Drawing an empty track for it would assert a measurement nobody made.
     */
    "reported": boolean;

    /**
     * Declared says whether anything requests this dimension. Ephemeral
     * storage is usually declared by nothing at all, which is a finding about
     * the cluster rather than a gap in the data.
     */
    "declared": boolean;
}

/**
 * RestartHotspot is a pod worth looking at because it keeps restarting.
 */
export interface RestartHotspot {
    "namespace": string;
    "name": string;
    "restarts": number;
    "reason": string;
    "ageSeconds": number;
    "healthy": boolean;
}

/**
 * RevisionDTO is one recorded revision of a Deployment, StatefulSet or
 * DaemonSet's pod template — what RolloutHistory returns, over the wire.
 */
export interface RevisionDTO {
    /**
     * Number is the revision number Kubernetes assigned.
     */
    "number": number;

    /**
     * Name is the owning ReplicaSet's or ControllerRevision's own name.
     */
    "name": string;

    /**
     * CreatedAt is the creation timestamp in RFC 3339, empty if unknown.
     */
    "createdAt": string;

    /**
     * AgeSeconds is the age at the time of the call.
     */
    "ageSeconds": number;

    /**
     * Current marks the revision presently in use.
     */
    "current": boolean;

    /**
     * Replicas is how many pods this revision has — zero for a StatefulSet
     * or DaemonSet revision, which is a stored patch rather than a scaled
     * object. See domain.Revision.Replicas.
     */
    "replicas": number;

    /**
     * Images are the pod template's container images.
     */
    "images": string[] | null;

    /**
     * ChangeCause is the kubernetes.io/change-cause annotation, empty when
     * the object that produced this revision never carried one.
     */
    "changeCause": string;

    /**
     * TemplateYAML is the pod template this revision would roll back to,
     * for the History tab's diff view.
     */
    "templateYaml": string;
}

/**
 * RoleBindingRef is one RoleBinding or ClusterRoleBinding.
 */
export interface RoleBindingRef {
    /**
     * Kind is "RoleBinding" or "ClusterRoleBinding".
     */
    "kind": string;

    /**
     * Name is the binding's name.
     */
    "name": string;

    /**
     * Namespace is the RoleBinding's namespace, empty for a
     * ClusterRoleBinding.
     */
    "namespace": string;

    /**
     * RoleRefKind is the referenced role's kind.
     */
    "roleRefKind": string;

    /**
     * RoleRefName is the referenced role's name.
     */
    "roleRefName": string;

    /**
     * Subjects are the accounts it grants the role to.
     */
    "subjects": RBACSubject[] | null;
}

/**
 * RoleInspection is one Role or ClusterRole, what references it, and what its
 * rules permit.
 */
export interface RoleInspection {
    /**
     * Scope is "cluster" or "namespace".
     */
    "scope": string;

    /**
     * Namespace is the Role's namespace, empty for a ClusterRole.
     */
    "namespace": string;

    /**
     * Name is the role's name.
     */
    "name": string;

    /**
     * Kind is the Kubernetes kind Scope names.
     */
    "kind": string;

    /**
     * Status says whether the role itself could be read.
     */
    "status": string;

    /**
     * Refusal is the sentence to show when Status is not "answered".
     */
    "refusal": string;

    /**
     * Rules are the role's own rules.
     */
    "rules": PolicyRule[] | null;

    /**
     * BindingsStatus says whether the bindings could be listed. Separate
     * from Status because the two are separate reads and fail apart.
     */
    "bindingsStatus": string;

    /**
     * BindingsRefusal is the sentence to show when BindingsStatus is not
     * "answered".
     */
    "bindingsRefusal": string;

    /**
     * Bindings are the bindings that reference this role.
     */
    "bindings": RoleBindingRef[] | null;

    /**
     * Findings are the blast-radius flags, worst first.
     */
    "findings": RBACFinding[] | null;
}

/**
 * RollbackOutcomeDTO reports what RollbackWorkload actually did — what
 * domain.RollbackOutcome carries, over the wire.
 */
export interface RollbackOutcomeDTO {
    /**
     * ToRevision is the revision number rolled back to.
     */
    "toRevision": number;

    /**
     * DryRun reports whether this outcome came from a server-side dry run —
     * nothing was persisted when it is true.
     */
    "dryRun": boolean;
}

/**
 * Sample is one recorded measurement of a cluster, as the chart plots it.
 * 
 * Timestamps go out as Unix milliseconds rather than formatted strings: this
 * is chart data, and every charting library wants a number. Everything else is
 * raw too — the frontend scales and formats, because a chart axis needs to
 * compare values the backend cannot know the units of in advance.
 */
export interface Sample {
    /**
     * At is Unix milliseconds, UTC.
     */
    "at": number;

    /**
     * CPU figures are millicores; memory figures are bytes.
     */
    "cpuUsage": number;
    "cpuRequests": number;
    "cpuAllocatable": number;
    "memoryUsage": number;
    "memoryRequests": number;
    "memoryAllocatable": number;
    "podsScheduled": number;
    "podsNotReady": number;
    "nodesReady": number;
    "nodesTotal": number;

    /**
     * Measured is false when no metrics API answered at that moment. The
     * usage series must break rather than plot zero, which would read as an
     * idle cluster.
     */
    "measured": boolean;
}

/**
 * SeriesResult is a cluster's history and an honest account of its extent.
 */
export interface SeriesResult {
    "samples": Sample[] | null;

    /**
     * SpanSeconds is how long the returned samples actually cover, which lets
     * the UI say "the last 40 minutes" instead of implying it has everything.
     */
    "spanSeconds": number;

    /**
     * RetentionDays is the configured retention; 0 means nothing is recorded.
     */
    "retentionDays": number;

    /**
     * IntervalSeconds is how often a sample is taken, which tells the UI how
     * long to wait before a second point can possibly exist.
     */
    "intervalSeconds": number;

    /**
     * Recording reports whether sampling is on at all.
     */
    "recording": boolean;
}

/**
 * StorageClassUsage is one class's share of the provisioned total.
 */
export interface StorageClassUsage {
    "name": string;
    "volumes": number;
    "size": string;

    /**
     * Share is this class's percentage of the provisioned total, for the bar.
     */
    "share": number;
}

/**
 * StorageSummary is the cluster's persistent storage at a glance.
 */
export interface StorageSummary {
    /**
     * Provisioned, Unbound and Orphaned are pre-formatted for display.
     */
    "provisioned": string;
    "unbound": string;
    "orphaned": string;

    /**
     * OrphanedBytes drives whether the row is shown at all, which a formatted
     * string cannot answer.
     */
    "orphanedBytes": number;

    /**
     * Claims and Volumes count each by phase, most interesting first.
     */
    "claims": PhaseCount[] | null;
    "volumes": PhaseCount[] | null;
    "totalClaims": number;
    "totalVolumes": number;

    /**
     * Largest is the biggest bound volume, pre-formatted, with the name that
     * makes it actionable.
     */
    "largest": string;
    "largestName": string;
    "largestBytes": number;

    /**
     * UnboundBytes drives whether the waiting row says anything.
     */
    "unboundBytes": number;

    /**
     * Classes breaks the provisioned total down, largest first.
     */
    "classes": StorageClassUsage[] | null;
}

/**
 * Subject is one object a finding is about.
 */
export interface Subject {
    "kind": string;
    "namespace": string;
    "name": string;

    /**
     * Detail is the specific fact about this object — an exit reason, a
     * replica shortfall, the scheduler's explanation.
     */
    "detail": string;
}

/**
 * SubjectRules is the answer to "what can this kubeconfig do here".
 */
export interface SubjectRules {
    /**
     * Namespace is the namespace the review actually asked about, which is
     * not always the one the tab is filtered to — a rules review has no
     * cluster-wide form.
     */
    "namespace": string;

    /**
     * Status is answered, forbidden, absent or failed.
     */
    "status": string;

    /**
     * Refusal is the sentence to show when Status is not "answered".
     */
    "refusal": string;

    /**
     * Namespaced holds the rules that apply to objects in Namespace.
     */
    "namespaced": PolicyRule[] | null;

    /**
     * ClusterScoped holds the non-resource URL rules, which are the API
     * server's own paths and so belong to the cluster rather than to the
     * namespace asked about.
     */
    "clusterScoped": PolicyRule[] | null;

    /**
     * Incomplete is the API server's own warning that it could not enumerate
     * everything.
     */
    "incomplete": boolean;

    /**
     * IncompleteReason is the evaluation error behind Incomplete, verbatim.
     */
    "incompleteReason": string;
}

/**
 * TableColumn describes one column of a generic table.
 */
export interface TableColumn {
    "name": string;

    /**
     * Type is "string", "integer", "number" or "date", so the UI can align
     * and sort correctly.
     */
    "type": string;

    /**
     * Wide marks columns from the extended set, which start hidden.
     */
    "wide": boolean;
    "description": string;
}

/**
 * TableRow is one object rendered as cells.
 */
export interface TableRow {
    "name": string;
    "namespace": string;
    "cells": string[] | null;

    /**
     * Labels are the object's labels, from the row's own metadata.
     */
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations are only the projected keys — see Pod.Annotations.
     */
    "annotations": { [_ in string]?: string } | null;
}

/**
 * Termination is a container's previous death, explained.
 */
export interface Termination {
    "exitCode": number;
    "signal": number;

    /**
     * Reason is the kubelet's word — "OOMKilled", "Error", "Completed".
     */
    "reason": string;

    /**
     * Diagnosis is the sentence to show. Written in the domain, because
     * deciding that a 137 without an OOMKilled reason is a grace-period
     * expiry rather than a memory limit is a judgement, not a lookup.
     */
    "diagnosis": string;

    /**
     * Alarming says whether to colour it. A clean SIGTERM during a rollout
     * is how every deployment stops a container and is not a fault.
     */
    "alarming": boolean;

    /**
     * FinishedAt is RFC 3339, empty if unknown; LifetimeSeconds is how long
     * it ran before dying, zero when the timestamps do not allow the sum.
     */
    "finishedAt": string;
    "lifetimeSeconds": number;
}

/**
 * TopConsumers is what is actually using the cluster.
 */
export interface TopConsumers {
    "byCpu": Consumer[] | null;
    "byMemory": Consumer[] | null;
    "measured": boolean;
}

/**
 * UpdateStatus is what the interface shows about newer releases.
 */
export interface UpdateStatus {
    /**
     * State is "current", "available", "disabled" or "unknown".
     * 
     * FOUR STATES, NOT A BOOLEAN, because they need different treatment and
     * three of them must be silent. "unknown" in particular is the ordinary
     * condition on an airgapped machine or behind a corporate NAT that has
     * spent GitHub's 60-an-hour anonymous budget, and rendering it as a
     * failure would put a permanent warning in front of somebody whose only
     * problem is a firewall doing its job.
     */
    "state": string;

    /**
     * Installed is the running build.
     */
    "installed": string;

    /**
     * Latest is the newest published release, empty unless one was read.
     */
    "latest": string;

    /**
     * URL is the release page. Never a direct download: PodSteer does not
     * update itself, and the operator installs it however they did before.
     */
    "url": string;
}

/**
 * UpgradeSummary is the one-line version of what the upgrade-impact findings
 * found, for the overview header's "check against" selector — the findings
 * themselves are already in Overview.Findings, this only saves the frontend
 * from filtering and counting them by category.
 */
export interface UpgradeSummary {
    /**
     * TargetMinor is the Kubernetes minor the assessment was made against,
     * e.g. "1.33". Empty means no target could be placed at all — Version
     * was unparseable — which the UI reads differently from "assessed and
     * found nothing".
     */
    "targetMinor": string;

    /**
     * Count is how many upgrade-impact findings were raised, at any
     * severity.
     */
    "count": number;
}

/**
 * VersionCount is one kubelet version and how many nodes run it.
 * 
 * A slice rather than a map because Wails generates a TypeScript index
 * signature for maps, which is awkward to iterate in order — and order is the
 * point here.
 */
export interface VersionCount {
    "version": string;
    "nodes": number;
}

/**
 * VulnerabilitySummary is what a scanner already running in the cluster
 * recorded about ONE workload, as a pod row reads it.
 * 
 * FIVE NUMBERS AND A COUNT, never a verdict. Nothing here ranks a workload
 * against another or decides what "acceptable" is: an operator running a
 * scanner has a policy already, and the row shows what their scanner found.
 */
export interface VulnerabilitySummary {
    /**
     * Subject is "Kind/name" — the same shape Pod.ControlledBy carries, which
     * is how a row finds its own summary without either side re-deriving the
     * other's format.
     */
    "subject": string;
    "critical": number;
    "high": number;
    "medium": number;
    "low": number;

    /**
     * Unknown is the scanner's own bucket for a finding whose severity its
     * sources do not state. Carried rather than folded into Low.
     */
    "unknown": number;

    /**
     * Reports is how many reports were summed — one per container. It is what
     * keeps "scanned, and clean" distinguishable from "not scanned", which a
     * row of five zeroes cannot say on its own.
     */
    "reports": number;
}

/**
 * Workload is a pod-managing controller as presented to the UI.
 */
export interface Workload {
    "kind": string;
    "name": string;
    "namespace": string;

    /**
     * Status is the single word to show: Running, Degraded, Rolling,
     * Unavailable, Suspended or "Scaled to zero".
     */
    "status": string;

    /**
     * Ready is the ready/desired count formatted for display, "2/3".
     */
    "ready": string;
    "desired": number;
    "readyCount": number;
    "current": number;
    "updated": number;
    "available": number;
    "isHealthy": boolean;
    "isRolling": boolean;
    "suspended": boolean;

    /**
     * Images are the pod template's container images.
     */
    "images": string[] | null;

    /**
     * ControlledBy names the controlling owner, e.g. a Deployment behind a
     * ReplicaSet. Empty when nothing controls it.
     */
    "controlledBy": string;

    /**
     * Schedule is a CronJob's cron expression.
     */
    "schedule": string;
    "lastScheduled": string;
    "labels": { [_ in string]?: string } | null;

    /**
     * Annotations carries only the GitOps keys — see gitOpsAnnotations in the
     * k8s mapper for why it is not the whole set.
     */
    "annotations": { [_ in string]?: string } | null;
    "createdAt": string;
    "ageSeconds": number;
}

/**
 * WorkloadKindSummary counts one controller kind.
 */
export interface WorkloadKindSummary {
    "kind": string;
    "kindId": string;
    "title": string;
    "total": number;
    "healthy": number;
    "rolling": number;
    "degraded": number;
}
