// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationAPI shows OS notifications, and does nothing else.
 * 
 * It is a bound service rather than a runtime call the frontend makes
 * directly because the webview has no route to the desktop: Wails' notification
 * support is Go-side (UNUserNotificationCenter on macOS, toast XML on
 * Windows, D-Bus on Linux), and the browser Notification API the page could
 * otherwise reach is exactly the sort of thing the CSP and the no-network
 * commitment exist to keep out of the page.
 * 
 * IT IS ALSO THE ONLY PART OF THAT SUPPORT THE PAGE CAN REACH. Wails v3
 * ships notifications as a service of its own, whose exported methods would
 * all be bound if it were registered — the removal and category-management
 * surface included. So App starts it by hand and keeps the handle, and these
 * three methods are the whole of what crosses the bridge. See
 * App.StartNotifications.
 * 
 * WHAT IT DOES NOT DO IS DECIDE ANYTHING. Whether a finding is new, whether
 * it is snoozed, whether the operator asked for this at all and whether one
 * has been sent too recently are all decided in the frontend, beside the
 * assessment diff those questions are about — see web/src/lib/notify.ts. This
 * end is the delivery mechanism and the platform's own honesty about what it
 * can deliver.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capability reports what this platform will actually do.
 * 
 * Asked when the Settings pane opens, so the switch can say why it will do
 * nothing rather than sitting there looking as though it works — the same job
 * alertPlayer.available does for the sound.
 */
export function Capability(): $CancellablePromise<$models.NotificationCapability> {
    return $Call.ByID(3049110426);
}

/**
 * Notify posts one notification.
 * 
 * NOTHING IS LOGGED BUT THE FACT OF IT. The title is a finding's own rule
 * name and could reasonably be logged, but a log line that quoted the body
 * would be a second copy of whatever the body carried, in a file, which is
 * the shape of mistake this whole feature is fenced against. The count of
 * notifications is what an engineer debugging this needs.
 * 
 * DO-NOT-DISTURB IS THE OPERATING SYSTEM'S, and this is where that is honest
 * rather than implemented: macOS Focus, Windows Focus Assist and a GNOME or
 * KDE notification daemon's own quiet mode all apply AFTER delivery, in the
 * notification centre itself, and none of them is readable through any API
 * Wails exposes. So PodSteer posts, and the platform decides whether to
 * present — which is the behaviour every well-behaved desktop application
 * has. Inventing a do-not-disturb check here would mean guessing at a state
 * this process cannot see, and guessing wrong in the direction that silences
 * an alarm somebody asked for.
 */
export function Notify(request: $models.NotificationRequest): $CancellablePromise<void> {
    return $Call.ByID(3283138469, request);
}

/**
 * Request asks the operating system for permission to post notifications.
 * 
 * Called when the operator turns the preference ON, and never before: on
 * macOS this is a visible system prompt, and one that arrives unprompted is
 * one people deny. On platforms with no such concept it is a no-op returning
 * true.
 */
export function Request(): $CancellablePromise<boolean> {
    return $Call.ByID(1560747989);
}
