// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OverviewAPI exposes the cluster dashboard.
 * 
 * One call rather than a dozen: the assessment needs nodes, pods, controllers,
 * events and metrics together, and letting the frontend fetch them separately
 * would mean the dashboard reasoned about a cluster it saw at six different
 * moments — and would put the analysis in the browser, where it could not be
 * tested.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetOverview assesses a connected cluster.
 * 
 * An error here means the assessment could not be produced at all — in
 * practice, that the cluster is not connected. A cluster missing individual
 * sources still returns an overview, with those sources named in
 * Overview.Unavailable.
 */
export function GetOverview(clusterID: string): $CancellablePromise<$models.Overview> {
    return $Call.ByID(3211671495, clusterID);
}

/**
 * GetOverviewForTarget assesses a connected cluster the way GetOverview does,
 * but scores the upgrade-impact findings against a chosen Kubernetes minor
 * rather than the default of the next one — what the overview header's
 * "check against" selector calls when an operator picks a different target.
 * 
 * targetMinor is e.g. "1.33". An empty string asks for the default, the same
 * as GetOverview.
 */
export function GetOverviewForTarget(clusterID: string, targetMinor: string): $CancellablePromise<$models.Overview> {
    return $Call.ByID(1941407507, clusterID, targetMinor);
}
