// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RBACAPI exposes the RBAC explorer.
 * 
 * EVERY METHOD IS A READ AND EVERY METHOD IS ON DEMAND. Nothing here is
 * called by the refresh tick, and nothing here is cached: an allow or deny
 * decision shown from a previous instant could report a permission that has
 * since been revoked as still granted, which is the one answer this feature
 * must never give.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CanI answers one access review, for the current account or a named subject.
 * 
 * The API server decides. Its own allowed, denied and reason cross this
 * boundary untouched, and nothing in PodSteer evaluates a rule to second-guess
 * them.
 */
export function CanI(clusterID: string, request: $models.AccessRequest): $CancellablePromise<$models.AccessDecision> {
    return $Call.ByID(566573794, clusterID, request);
}

/**
 * InspectRole reads one Role or ClusterRole, finds the bindings referencing
 * it, and assesses what its rules permit.
 * 
 * scope is "cluster" or "namespace". Called when the panel is opened, and not
 * on any tick: it costs three requests, two of them cluster-wide lists.
 */
export function InspectRole(clusterID: string, scope: string, $namespace: string, name: string): $CancellablePromise<$models.RoleInspection> {
    return $Call.ByID(2205596809, clusterID, scope, $namespace, name);
}

/**
 * SubjectRules answers what the current credentials may do in one namespace.
 * 
 * ONE REQUEST for the whole answer — SelfSubjectRulesReview enumerates every
 * rule that applies, so this is not one access check per verb per resource.
 */
export function SubjectRules(clusterID: string, $namespace: string): $CancellablePromise<$models.SubjectRules> {
    return $Call.ByID(3906964484, clusterID, $namespace);
}
