// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsAPI exposes the backend-owned settings to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddKubeconfigFile adds a single kubeconfig file to the operator's sources.
 */
export function AddKubeconfigFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(382093972, path);
}

/**
 * AddKubeconfigFolder adds a folder of kubeconfig files.
 * 
 * Scanned by the same code PODSTEER_KUBECONFIG_DIR is, so what it contributes
 * is decided the same way: dotfiles, subdirectories and anything that does not
 * parse as a kubeconfig are skipped.
 */
export function AddKubeconfigFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(265306298, path);
}

/**
 * GetKubeconfigSources reports the composed loading list, in precedence order.
 */
export function GetKubeconfigSources(): $CancellablePromise<$models.KubeconfigSource[] | null> {
    return $Call.ByID(2490900853);
}

/**
 * GetState reports where the settings live and whether they can be saved.
 */
export function GetState(): $CancellablePromise<$models.SettingsState> {
    return $Call.ByID(3938522299);
}

/**
 * MoveKubeconfigSource shifts one of the operator's sources by delta places.
 * 
 * Order is precedence, so this decides which of two sources defining the same
 * context name wins. A move past either end is clamped rather than refused.
 */
export function MoveKubeconfigSource(path: string, delta: number): $CancellablePromise<void> {
    return $Call.ByID(763693145, path, delta);
}

/**
 * RemoveKubeconfigSource drops one of the operator's own sources.
 * 
 * It removes an ENTRY, never a file: nothing on disk is touched, and the
 * kubeconfig it named is exactly as it was.
 */
export function RemoveKubeconfigSource(path: string): $CancellablePromise<void> {
    return $Call.ByID(3157403548, path);
}
