// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsAPI exposes the backend-owned settings to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddKubeconfigFile adds a single kubeconfig file to the operator's sources.
 */
export function AddKubeconfigFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(382093972, path);
}

/**
 * AddKubeconfigFolder adds a folder of kubeconfig files.
 * 
 * Scanned by the same code PODSTEER_KUBECONFIG_DIR is, so what it contributes
 * is decided the same way: dotfiles, subdirectories and anything that does not
 * parse as a kubeconfig are skipped.
 */
export function AddKubeconfigFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(265306298, path);
}

/**
 * GetClusterSettings reports the switches for each named cluster.
 * 
 * A LIST IN ONE CALL rather than a call per row. The section lists every open
 * tab's context plus any context that has a stored entry, and asking for them
 * one at a time would be a bridge round trip per context in somebody's
 * kubeconfig every time the section is opened — for an answer that is a map
 * lookup in this process.
 * 
 * A cluster with no stored entry is reported with the DEFAULTS rather than
 * omitted, because absence and "off, ranked pick, filter" are the same thing
 * (see domain.Settings.Cluster) and a caller that had to tell them apart
 * would be re-deriving that here.
 */
export function GetClusterSettings(clusterIds: string[] | null): $CancellablePromise<$models.ClusterSettings[] | null> {
    return $Call.ByID(3325956685, clusterIds);
}

/**
 * GetKubeconfigSources reports the composed loading list, in precedence order.
 */
export function GetKubeconfigSources(): $CancellablePromise<$models.KubeconfigSource[] | null> {
    return $Call.ByID(2490900853);
}

/**
 * GetProxy reports the proxy setting as it currently stands.
 */
export function GetProxy(): $CancellablePromise<$models.ProxySettings> {
    return $Call.ByID(1134859170);
}

/**
 * GetState reports where the settings live and whether they can be saved.
 */
export function GetState(): $CancellablePromise<$models.SettingsState> {
    return $Call.ByID(3938522299);
}

/**
 * MoveKubeconfigSource shifts one of the operator's sources by delta places.
 * 
 * Order is precedence, so this decides which of two sources defining the same
 * context name wins. A move past either end is clamped rather than refused.
 */
export function MoveKubeconfigSource(path: string, delta: number): $CancellablePromise<void> {
    return $Call.ByID(763693145, path, delta);
}

/**
 * RemoveKubeconfigSource drops one of the operator's own sources.
 * 
 * It removes an ENTRY, never a file: nothing on disk is touched, and the
 * kubeconfig it named is exactly as it was.
 */
export function RemoveKubeconfigSource(path: string): $CancellablePromise<void> {
    return $Call.ByID(3157403548, path);
}

/**
 * SetMetricsQuery records whether a discovered monitoring backend may be
 * queried for one cluster, which one answers, and on what terms.
 * 
 * NOTHING HERE SENDS A QUERY, though what it records now decides whether a
 * chart may: this writes the switch, and application.MetricsQueryService is
 * what consults it before anything reaches a monitoring backend. Off is the
 * default and off means no request is made.
 * 
 * LOOSE STRINGS, VALIDATED IN THE DOMAIN. An unknown mode, an unknown policy
 * or a preferred backend that is not a pair of DNS-1123 labels is refused by
 * domain.Settings.Validate before anything is written — a bad value arriving
 * from the interface is a bug in the interface, and this file is the one that
 * ends up in a support bundle.
 * 
 * Passing both preferred names empty is how the operator returns to the ranked
 * pick, and it is the state in which no object name is written at all.
 */
export function SetMetricsQuery(clusterId: string, mode: string, preferredNamespace: string, preferredService: string, fleetPolicy: string): $CancellablePromise<void> {
    return $Call.ByID(4004385389, clusterId, mode, preferredNamespace, preferredService, fleetPolicy);
}

/**
 * SetProxy records it, and rebuilds the clients of every open cluster so it
 * applies to what the operator is looking at rather than only to the next
 * connection.
 * 
 * LOOSE STRINGS, VALIDATED IN THE DOMAIN, exactly as SetMetricsQuery's are:
 * an unknown mode, a URL that is not absolute http/https/socks5, or one
 * carrying a username and password is refused before anything is written.
 */
export function SetProxy(mode: string, url: string, noProxy: string): $CancellablePromise<void> {
    return $Call.ByID(1393179942, mode, url, noProxy);
}
