// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemAPI exposes application-level facts and shell integration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseDirectory opens the native folder picker and returns the operator's
 * choice — the destination of a download, or a folder to upload.
 * 
 * The path is returned to the frontend rather than acted on here, unlike
 * SaveTextFile, because the thing that will use it — FileCopyAPI — is a
 * transfer the operator has yet to start and may still change their mind
 * about. Handing a path back is safe in this direction: the frontend can
 * only ever pass it to a Go method that checks it is a directory and writes
 * nothing but what the container sent through the ArchivePort's rules. An
 * empty path means the operator cancelled, which is not an error.
 */
export function ChooseDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(3313545190, title);
}

/**
 * ChooseFile opens the native file picker and returns the operator's
 * choice — a file to upload into a container. The same conventions as
 * ChooseDirectory: the path is only ever consumed by FileCopyAPI, which
 * reads it through the ArchivePort, and "" means cancelled.
 */
export function ChooseFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(3759010849, title);
}

/**
 * Credits returns every dependency PodSteer ships, with its licence.
 * 
 * Not decoration: MIT, BSD, ISC and Apache-2.0 all require the licence and its
 * copyright notice to be distributed with the binary, and a desktop
 * application has nowhere else to put them. The inventory is generated from
 * what actually ships and embedded at build time, so it cannot drift away from
 * the dependencies it describes.
 */
export function Credits(): $CancellablePromise<$models.Credit[] | null> {
    return $Call.ByID(2055398216);
}

/**
 * Info returns the running application's identity.
 */
export function Info(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(4176267110);
}

/**
 * LicenceText returns one licence's full text.
 * 
 * Fetched on demand rather than sent with the list: the texts total far more
 * than the summary does, and nobody reads more than one at a time.
 */
export function LicenceText(textID: string): $CancellablePromise<string> {
    return $Call.ByID(144193754, textID);
}

/**
 * OpenURL opens an address in the operator's default browser or mail client.
 * 
 * The webview must never navigate away from the bundled application: doing so
 * would replace the UI with a web page and leave no way back, since there is
 * no address bar. Handing the URL to the OS is the only correct way to follow
 * a link from a desktop app.
 * 
 * Only the schemes in allowedURLSchemes are accepted. Without that check a
 * crafted "file://" or "javascript:" URL reaching this method would ask the
 * shell to open something it should not — and this method is callable from
 * the webview.
 */
export function OpenURL(raw: string): $CancellablePromise<void> {
    return $Call.ByID(3261014791, raw);
}

/**
 * ReadTextFile opens a native file picker and returns what the chosen file
 * contains.
 * 
 * The file is read HERE rather than handed to the frontend as a path, for the
 * same reason ReadKubeconfigFile is: the webview cannot open files and should
 * not be able to. That is also why this exists rather than ChooseFile being
 * reused — ChooseFile returns a PATH, which is only ever useful to a Go method
 * that will act on it, and nothing in the webview can turn one into content.
 * 
 * An empty returned string means the operator cancelled, which is not an
 * error — the same convention as ChooseDirectory and ReadKubeconfigFile. An
 * empty FILE is refused instead of being returned as a cancellation, because
 * the two would otherwise be indistinguishable to the caller.
 */
export function ReadTextFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(3290181867, title);
}

/**
 * SaveTextFile opens a native save dialog seeded with suggestedName and
 * writes content to wherever the operator chose.
 * 
 * This is the one place PodSteer writes a file the OPERATOR picked the
 * location for, rather than one of the fixed per-user paths — history and
 * display preferences — everything else in SECURITY.md enumerates. The write
 * happens here, in Go, because the webview cannot touch the filesystem and
 * should not be able to: handing the frontend a path instead would mean
 * trusting whatever content it sent, unauthenticated, to land wherever it
 * said.
 * 
 * An empty returned path means the operator cancelled the dialog, which is
 * not an error — see ReadKubeconfigFile for the same convention on the way
 * in.
 */
export function SaveTextFile(suggestedName: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(2129877442, suggestedName, content);
}
