// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalAPI exposes interactive terminal sessions to the frontend.
 * 
 * Unlike ExecInPod (which is request/response), TerminalAPI maintains
 * persistent bidirectional streams with TTY allocation. This enables
 * interactive programs like top, htop, vim, less, and interactive shells.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DetectAgents reports the coding agents present on the operator's PATH.
 * 
 * FOUND, NOT INSTALLED, and that distinction is the whole feature: PodSteer
 * looks for binaries the operator already has and offers those. It downloads
 * nothing, suggests installing nothing, and an empty list is an ordinary
 * answer for a machine with no agent on it.
 */
export function DetectAgents(): $CancellablePromise<$models.CodingAgentDTO[] | null> {
    return $Call.ByID(2154436246);
}

/**
 * LocalShellSupported reports whether a local shell can be opened here.
 * 
 * Asked by the interface before the control is offered, so an operator on a
 * platform without it reads one honest sentence rather than pressing something
 * that fails.
 */
export function LocalShellSupported(): $CancellablePromise<$models.LocalShellSupportDTO> {
    return $Call.ByID(3370224510);
}

/**
 * Resize notifies the terminal session of a window size change.
 * 
 * This triggers the Kubernetes API to send a SIGWINCH to the process
 * running in the container, so programs like top and vim redraw correctly.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(4169965023, sessionID, cols, rows);
}

/**
 * StartAgentSession opens the operator's own coding agent CLI in a local
 * shell's place, in the same environment, with an opening prompt naming the
 * cluster and the object they had open. It returns the session ID.
 * 
 * NOTHING IS SENT ANYWHERE BY PODSTEER. This starts a local process and hands
 * it an argument; whatever the agent then does with its own provider is
 * between the operator and the tool they installed. That is what keeps this
 * consistent with the no-account, no-telemetry commitment — there is no
 * PodSteer service in the path, and adding one would be a different decision
 * requiring a different record.
 * 
 * readOnly is the default the launcher offers: it sets a marker in the
 * environment and asks, in the prompt, for read-only kubectl unless the
 * operator says otherwise. A REQUEST, not a restriction — the agent holds the
 * operator's own credentials and nothing here can narrow them.
 */
export function StartAgentSession(clusterContext: string, agent: string, kind: string, $namespace: string, name: string, readOnly: boolean, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(2192729154, clusterContext, agent, kind, $namespace, name, readOnly, cols, rows);
}

/**
 * StartAttachSession creates a new interactive session attached to a
 * container's own running process — PID 1, whatever the image's
 * ENTRYPOINT/CMD started — rather than the new shell StartSession opens.
 * 
 * It shares StartSession's machinery end to end: the same session registry,
 * the same "terminal:data"/"terminal:exit" events, and Write/Resize/StopSession
 * work identically on either kind of session, so the frontend need not know
 * which one it opened once it has the session ID back.
 * 
 * Returns the session ID.
 */
export function StartAttachSession(clusterID: string, $namespace: string, podName: string, containerName: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(531957880, clusterID, $namespace, podName, containerName, cols, rows);
}

/**
 * StartDebugSession adds an ephemeral debug container to a pod — the way
 * `kubectl debug -it POD --image=… --target=CONTAINER` does — waits for it to
 * run, and opens an interactive shell into it through the SAME exec path
 * StartSession uses. It returns the session ID.
 * 
 * The container it adds cannot be removed: an ephemeral container stays in the
 * pod's spec until the pod is deleted, which is Kubernetes' behaviour and what
 * the dialog offering this states. There is therefore nothing to track and no
 * teardown here — unlike a node shell, whose pod PodSteer must delete.
 */
export function StartDebugSession(clusterID: string, $namespace: string, podName: string, targetContainer: string, image: string, command: string[] | null, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1622708476, clusterID, $namespace, podName, targetContainer, image, command, cols, rows);
}

/**
 * StartLocalSession opens the operator's own login shell on THIS machine, with
 * KUBECONFIG set to the same files PodSteer reads and a notice naming the open
 * tab's context. It returns the session ID.
 * 
 * NO READ-ONLY REFUSAL, and its absence is deliberate rather than an omission.
 * Every other Start method here checks ManagementService.ReadOnly first,
 * because each of them makes PodSteer write to a cluster. This one starts a
 * process on the operator's laptop that PodSteer neither mediates nor observes
 * — the guard is about this application's own writes, and a shell somebody
 * opened on their own machine with their own credentials is not something it
 * can or should police. The pane says exactly that, and so does SECURITY.md.
 */
export function StartLocalSession(clusterContext: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(792603900, clusterContext, cols, rows);
}

/**
 * StartNodeShellSession creates a privileged pod on a node that enters the
 * node's host namespaces — the way `kubectl node-shell` and Lens do — and
 * attaches to its login shell. It returns the session ID.
 * 
 * The pod is DELETED when this session ends, so the pod and the terminal that
 * makes it useful are bound together the way CLAUDE.md's node-shell lifecycle
 * requires: nothing privileged is left running on a node once the operator has
 * closed the shell. The activeDeadlineSeconds the pod carries is only a
 * backstop for the one case this cannot cover — PodSteer crashing.
 */
export function StartNodeShellSession(clusterID: string, $namespace: string, nodeName: string, image: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(2466805875, clusterID, $namespace, nodeName, image, cols, rows);
}

/**
 * StartSession creates a new interactive terminal session in a pod container.
 * 
 * It allocates a PTY and starts a shell (/bin/sh). The session streams
 * stdout/stderr to the frontend via "terminal:data" events. The frontend
 * sends keystrokes via TerminalWrite.
 * 
 * Returns the session ID.
 */
export function StartSession(clusterID: string, $namespace: string, podName: string, containerName: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1033105407, clusterID, $namespace, podName, containerName, cols, rows);
}

/**
 * StopSession terminates an active terminal session.
 */
export function StopSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4012052937, sessionID);
}

/**
 * Write sends data to the terminal's stdin.
 * 
 * This is called by the frontend for every keystroke or paste operation.
 * The data may contain raw bytes including escape sequences for special keys.
 */
export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(995535914, sessionID, data);
}
