// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TopologyAPI exposes the namespace topology to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportTopologyPNG writes a PNG the page rendered to wherever the operator
 * picks in a save dialog, and returns the path — "" when they cancelled.
 * 
 * The image arrives as base64 (a `data:image/png;base64,` prefix is
 * accepted) and is checked to BE a PNG before anything is written: the page
 * cannot touch the filesystem, and this is not a general file writer.
 */
export function ExportTopologyPNG(suggestedName: string, pngBase64: string): $CancellablePromise<string> {
    return $Call.ByID(2510225256, suggestedName, pngBase64);
}

/**
 * Release stops `topology:changed` for a cluster, for when its topology page
 * closes. Optional: a drawn scope also expires on its own.
 */
export function Release(clusterID: string): $CancellablePromise<void> {
    return $Call.ByID(3674794935, clusterID);
}

/**
 * Topology draws the namespaces of one cluster, or all of them. Drawing a
 * scope also subscribes it to `topology:changed`.
 */
export function Topology(clusterID: string, namespaces: string[] | null, all: boolean): $CancellablePromise<$models.TopologyGraph> {
    return $Call.ByID(4220567267, clusterID, namespaces, all);
}
