// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrafficAPI is the topology's traffic layer, bound to the frontend.
 * 
 * LIKE MetricsQueryAPI, NO PARAMETER IS AN EXPRESSION OR A URL: a source and
 * a window are each one of a fixed set, validated here, and namespaces are
 * DNS-1123 labels before they go anywhere near a matcher. Nothing here is
 * called on a tick; the page asks when the layer is switched on.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Sources says which traffic sources the cluster's monitoring backend holds.
 */
export function Sources(clusterID: string): $CancellablePromise<$models.TrafficSources> {
    return $Call.ByID(914644462, clusterID);
}

/**
 * Traffic reads one source over one window for the namespaces drawn.
 */
export function Traffic(clusterID: string, namespaces: string[] | null, all: boolean, source: string, window: string): $CancellablePromise<$models.TrafficLayer> {
    return $Call.ByID(3982244021, clusterID, namespaces, all, source, window);
}
