// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateAPI answers whether a newer PodSteer has been published.
 * 
 * NOTHING CALLS THIS UNLESS THE OPERATOR LEFT THE CHECK ON. There is no timer
 * behind it and no goroutine: it acts when the interface asks, and the
 * interface asks only when the setting says so. `PODSTEER_UPDATE_CHECK=false`
 * stops it regardless, in the service, so no mistake in the UI can defeat it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate reports what is known about newer releases.
 * 
 * Returns a status rather than an error in every case. A check that could not
 * be made is not a failed operation — it is the "unknown" state, and raising
 * it as an error would put a dialog in front of somebody about a network they
 * may have deliberately closed.
 */
export function CheckForUpdate(force: boolean): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(3603237828, force);
}

/**
 * UpdateChecksPermitted reports whether this machine allows checking at all.
 * 
 * So the Settings toggle can show itself as overridden rather than pretending
 * to control something an administrator has already decided.
 */
export function UpdateChecksPermitted(): $CancellablePromise<boolean> {
    return $Call.ByID(2783243466);
}
