// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VendorCLIAPI offers the clusters a cloud CLI the operator has can see.
 * 
 * It hands back an OPAQUE ID per cluster and takes one back — never a name.
 * See application.VendorCLIService for why, and decision 12 for what this is
 * allowed to do at all.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops a listing that is still running.
 */
export function Cancel(provider: string): $CancellablePromise<void> {
    return $Call.ByID(463954687, provider);
}

/**
 * KubeconfigFor has the CLI write an entry for a chosen cluster and returns the
 * text.
 * 
 * THE TEXT, NOT THE WRITE. What comes back goes through PreviewKubeconfig and
 * AddKubeconfig exactly as a pasted document does, so the operator's kubeconfig
 * is still written in one place, with its backup, its atomic rename and its
 * refusal to touch current-context.
 */
export function KubeconfigFor(provider: string, selection: string): $CancellablePromise<string> {
    return $Call.ByID(3731388593, provider, selection);
}

/**
 * ListClusters asks one CLI which clusters it can see.
 */
export function ListClusters(provider: string): $CancellablePromise<$models.VendorClusterList> {
    return $Call.ByID(1606708882, provider);
}

/**
 * Providers reports the cloud CLIs PodSteer can drive and whether each is here.
 * 
 * A PATH LOOKUP AND NOTHING ELSE. Opening the Add cluster dialog must not run
 * anybody's cloud CLI.
 */
export function Providers(): $CancellablePromise<$models.VendorProvider[] | null> {
    return $Call.ByID(32824897);
}
