// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkloadAPI exposes the workload use cases to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplicationGraph returns the map of one application: the objects labelled
 * app.kubernetes.io/instance=<instance> in a namespace, and what they own.
 */
export function ApplicationGraph(clusterID: string, $namespace: string, instance: string): $CancellablePromise<$models.PodGraph> {
    return $Call.ByID(2451967040, clusterID, $namespace, instance);
}

/**
 * ExportPodsCSV writes every pod the query matches — every page, in the
 * table's order — as CSV to wherever the operator chooses, and returns the
 * path, or "" when they cancelled the dialog.
 * 
 * RENDERED AND WRITTEN HERE because the rows are: the webview holds one page
 * now, and shipping the whole list across the bridge to turn it into a file
 * would be the payload paging exists to avoid. The cells are the table's
 * own text (see podCSVCell) and the file is web/src/lib/csv.ts's format,
 * formula guard included. columns are the visible columns, in order.
 */
export function ExportPodsCSV(clusterID: string, $namespace: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null, query: $models.PodQuery, columns: $models.CSVColumn[] | null, suggestedName: string): $CancellablePromise<string> {
    return $Call.ByID(2660454060, clusterID, $namespace, annotationKeys, expressions, query, columns, suggestedName);
}

/**
 * ListApplicationPods returns the pods of one application, by the same rule
 * its map draws them with.
 */
export function ListApplicationPods(clusterID: string, $namespace: string, instance: string): $CancellablePromise<$models.Pod[] | null> {
    return $Call.ByID(2296016952, clusterID, $namespace, instance);
}

/**
 * ListApplications groups a cluster's workloads by the application they
 * belong to.
 * 
 * From Kubernetes' own recommended labels, which is the only thing that
 * standardises this — and which is a convention rather than a guarantee, so
 * the answer carries a count of what did not say.
 */
export function ListApplications(clusterID: string, $namespace: string): $CancellablePromise<$models.ApplicationInventory> {
    return $Call.ByID(3578460441, clusterID, $namespace);
}

/**
 * ListPodKeys names every pod the query matches, across every page — what
 * "select all matching" ticks. The page in the query is ignored.
 */
export function ListPodKeys(clusterID: string, $namespace: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null, query: $models.PodQuery): $CancellablePromise<$models.PodKey[] | null> {
    return $Call.ByID(730312501, clusterID, $namespace, annotationKeys, expressions, query);
}

/**
 * ListPods returns pods in the given namespace of a connected cluster.
 * 
 * An empty namespace lists across all of them, mirroring
 * `kubectl get pods --all-namespaces`.
 * 
 * annotationKeys names the annotations each row should carry — the ones the
 * operator has put on a custom column of this kind. Nothing else of the
 * annotation map crosses the bridge; see domain.Projection for why.
 */
export function ListPods(clusterID: string, $namespace: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null): $CancellablePromise<$models.Pod[] | null> {
    return $Call.ByID(651969882, clusterID, $namespace, annotationKeys, expressions);
}

/**
 * ListPodsForWorkload returns all pods owned by a specific workload.
 */
export function ListPodsForWorkload(clusterID: string, $namespace: string, kind: string, name: string): $CancellablePromise<$models.Pod[] | null> {
    return $Call.ByID(2437854440, clusterID, $namespace, kind, name);
}

/**
 * ListPodsOnNode returns the pods running on one node, across every namespace.
 */
export function ListPodsOnNode(clusterID: string, nodeName: string): $CancellablePromise<$models.Pod[] | null> {
    return $Call.ByID(3547040355, clusterID, nodeName);
}

/**
 * ListWorkloads returns controllers of the given kind.
 * 
 * The kind arrives as its display name — "Deployment", "StatefulSet" — which
 * is what the navigator already holds, so the frontend needs no second
 * vocabulary for the same six things.
 * 
 * annotationKeys is the same projection ListPods takes.
 */
export function ListWorkloads(clusterID: string, kind: string, $namespace: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null): $CancellablePromise<$models.Workload[] | null> {
    return $Call.ByID(2073109092, clusterID, kind, $namespace, annotationKeys, expressions);
}

/**
 * PodGraph returns the dependency chain around one pod.
 */
export function PodGraph(clusterID: string, $namespace: string, podName: string): $CancellablePromise<$models.PodGraph> {
    return $Call.ByID(777816347, clusterID, $namespace, podName);
}

/**
 * QueryPods returns one page of the pod table — what its search box, status
 * chips, sort and pager say — and the counts around it, rather than the whole
 * list. See domain.QueryPods, and CLAUDE.md, "The pod table is paged in Go".
 * 
 * annotationKeys and expressions are the list's projection, exactly as
 * ListPods takes them; query.Columns are the same custom columns as specs,
 * for what they add to the searchable text.
 */
export function QueryPods(clusterID: string, $namespace: string, annotationKeys: string[] | null, expressions: $models.CustomExpression[] | null, query: $models.PodQuery): $CancellablePromise<$models.PodPage> {
    return $Call.ByID(3494078594, clusterID, $namespace, annotationKeys, expressions, query);
}

/**
 * RolloutHistory returns the recorded revisions of a Deployment,
 * StatefulSet or DaemonSet's pod template, newest first — the History tab
 * in the drawer, and what a rollback picks a target revision from.
 */
export function RolloutHistory(clusterID: string, kind: string, $namespace: string, name: string): $CancellablePromise<$models.RevisionDTO[] | null> {
    return $Call.ByID(79112269, clusterID, kind, $namespace, name);
}

/**
 * WorkloadConsumption sums what each controller in a list is using, keyed by
 * "namespace/name".
 * 
 * A SECOND CALL BESIDE ListWorkloads rather than part of it. The controllers
 * are one cheap read and this is the namespace's pods and their metrics, so a
 * cluster with no metrics API, or an account that may list Deployments and
 * not pods, still gets its list — with the meters reading "not measured"
 * rather than nothing at all.
 */
export function WorkloadConsumption(clusterID: string, kind: string, $namespace: string): $CancellablePromise<{ [_ in string]?: $models.Consumption } | null> {
    return $Call.ByID(3725178438, clusterID, kind, $namespace);
}

/**
 * WorkloadGraph returns the dependency chain around one workload.
 */
export function WorkloadGraph(clusterID: string, $namespace: string, kind: string, name: string): $CancellablePromise<$models.PodGraph> {
    return $Call.ByID(1276837545, clusterID, $namespace, kind, name);
}

/**
 * WorkloadUsage sums what a controller's pods are consuming.
 * 
 * Read while a panel is open rather than alongside the controller list: it
 * costs that controller's pods and the namespace's metrics, and the figure is
 * only ever looked at one controller at a time.
 */
export function WorkloadUsage(clusterID: string, $namespace: string, kind: string, name: string): $CancellablePromise<$models.Consumption> {
    return $Call.ByID(2906749578, clusterID, $namespace, kind, name);
}
