// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetManifest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['BrowseAPI']['GetManifest'](arg1, arg2, arg3, arg4, arg5);
}

export function ListEvents(arg1, arg2) {
  return window['go']['wails']['BrowseAPI']['ListEvents'](arg1, arg2);
}

export function ListEventsForResource(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['BrowseAPI']['ListEventsForResource'](arg1, arg2, arg3, arg4);
}

export function ListKinds(arg1) {
  return window['go']['wails']['BrowseAPI']['ListKinds'](arg1);
}

export function ListTable(arg1, arg2, arg3) {
  return window['go']['wails']['BrowseAPI']['ListTable'](arg1, arg2, arg3);
}

export function RevealSecretKey(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['BrowseAPI']['RevealSecretKey'](arg1, arg2, arg3, arg4);
}
