// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssessCertificateRenewal(arg1) {
  return window['go']['wails']['BrowseAPI']['AssessCertificateRenewal'](arg1);
}

export function ClassifyConditions(arg1) {
  return window['go']['wails']['BrowseAPI']['ClassifyConditions'](arg1);
}

export function GetManifest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['BrowseAPI']['GetManifest'](arg1, arg2, arg3, arg4, arg5);
}

export function InspectTLSSecret(arg1, arg2, arg3) {
  return window['go']['wails']['BrowseAPI']['InspectTLSSecret'](arg1, arg2, arg3);
}

export function ListEvents(arg1, arg2, arg3) {
  return window['go']['wails']['BrowseAPI']['ListEvents'](arg1, arg2, arg3);
}

export function ListEventsForResource(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['BrowseAPI']['ListEventsForResource'](arg1, arg2, arg3, arg4);
}

export function ListKinds(arg1) {
  return window['go']['wails']['BrowseAPI']['ListKinds'](arg1);
}

export function ListTable(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['BrowseAPI']['ListTable'](arg1, arg2, arg3, arg4);
}

export function NamespaceInventory(arg1, arg2) {
  return window['go']['wails']['BrowseAPI']['NamespaceInventory'](arg1, arg2);
}

export function ObjectGraph(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['BrowseAPI']['ObjectGraph'](arg1, arg2, arg3, arg4);
}

export function RevealSecretKey(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['BrowseAPI']['RevealSecretKey'](arg1, arg2, arg3, arg4);
}

export function VulnerabilitySummaries(arg1, arg2) {
  return window['go']['wails']['BrowseAPI']['VulnerabilitySummaries'](arg1, arg2);
}
