// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetManifest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function ListEvents(arg1:string,arg2:string):Promise<Array<wails.Event>>;

export function ListEventsForResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<wails.Event>>;

export function ListKinds(arg1:string):Promise<Array<wails.ResourceKind>>;

export function ListTable(arg1:string,arg2:string,arg3:string):Promise<wails.ResourceTable>;

export function RevealSecretKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
