// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['wails']['ClusterAPI']['Connect'](arg1);
}

export function Connections() {
  return window['go']['wails']['ClusterAPI']['Connections']();
}

export function Disconnect(arg1) {
  return window['go']['wails']['ClusterAPI']['Disconnect'](arg1);
}

export function ListClusters() {
  return window['go']['wails']['ClusterAPI']['ListClusters']();
}

export function ListNamespaces(arg1) {
  return window['go']['wails']['ClusterAPI']['ListNamespaces'](arg1);
}

export function ListNodes(arg1) {
  return window['go']['wails']['ClusterAPI']['ListNodes'](arg1);
}
