// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function AddKubeconfig(arg1:string):Promise<wails.KubeconfigMerge>;

export function Connect(arg1:string):Promise<wails.Cluster>;

export function Connections():Promise<Array<wails.Cluster>>;

export function Disconnect(arg1:string):Promise<void>;

export function ListClusters():Promise<Array<wails.Cluster>>;

export function ListNamespaceSummaries(arg1:string):Promise<Array<wails.NamespaceSummary>>;

export function ListNamespaces(arg1:string):Promise<Array<wails.Namespace>>;

export function ListNodes(arg1:string):Promise<Array<wails.Node>>;

export function PreviewKubeconfig(arg1:string):Promise<wails.KubeconfigMerge>;

export function ReadKubeconfigFile():Promise<string>;
