// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveCluster() {
  return window['go']['wails']['ClusterAPI']['ActiveCluster']();
}

export function Connect(arg1) {
  return window['go']['wails']['ClusterAPI']['Connect'](arg1);
}

export function ListClusters() {
  return window['go']['wails']['ClusterAPI']['ListClusters']();
}

export function ListNamespaces() {
  return window['go']['wails']['ClusterAPI']['ListNamespaces']();
}
