// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ActiveCluster():Promise<wails.Cluster>;

export function Connect(arg1:string):Promise<wails.Cluster>;

export function ListClusters():Promise<Array<wails.Cluster>>;

export function ListNamespaces():Promise<Array<wails.Namespace>>;
