// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['wails']['FileCopyAPI']['Cancel'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['FileCopyAPI']['StartDownload'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartUpload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['FileCopyAPI']['StartUpload'](arg1, arg2, arg3, arg4, arg5, arg6);
}
