// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ListEvents(arg1:Array<string>,arg2:string):Promise<Array<wails.ClusterEvents>>;

export function ListPods(arg1:Array<string>,arg2:string):Promise<Array<wails.ClusterPods>>;

export function ListWorkloads(arg1:Array<string>,arg2:string):Promise<Array<wails.ClusterWorkloads>>;
