// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListEvents(arg1, arg2) {
  return window['go']['wails']['FleetAPI']['ListEvents'](arg1, arg2);
}

export function ListPods(arg1, arg2) {
  return window['go']['wails']['FleetAPI']['ListPods'](arg1, arg2);
}

export function ListWorkloads(arg1, arg2) {
  return window['go']['wails']['FleetAPI']['ListWorkloads'](arg1, arg2);
}
