// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRetention() {
  return window['go']['wails']['HistoryAPI']['GetRetention']();
}

export function GetSeries(arg1, arg2, arg3) {
  return window['go']['wails']['HistoryAPI']['GetSeries'](arg1, arg2, arg3);
}

export function SetRetention(arg1) {
  return window['go']['wails']['HistoryAPI']['SetRetention'](arg1);
}
