// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetSeries(arg1:string,arg2:number,arg3:number):Promise<wails.SeriesResult>;

export function GetSettings():Promise<wails.HistorySettings>;

export function SetRetention(arg1:number):Promise<void>;

export function SetSamplingInterval(arg1:number):Promise<void>;
