// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImageReport(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['InspectAPI']['ImageReport'](arg1, arg2, arg3, arg4);
}

export function ProbeFromHere(arg1, arg2) {
  return window['go']['wails']['InspectAPI']['ProbeFromHere'](arg1, arg2);
}

export function ProbeFromPod(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['InspectAPI']['ProbeFromPod'](arg1, arg2, arg3, arg4, arg5);
}
