// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ImageReport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<wails.ImageReport>;

export function ProbeFromHere(arg1:string,arg2:wails.ProbeSubjectInput):Promise<wails.ProbeResult>;

export function ProbeFromPod(arg1:string,arg2:string,arg3:string,arg4:string,arg5:wails.ProbeSubjectInput):Promise<wails.ProbeResult>;
