// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteResource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['ManagementAPI']['DeleteResource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecInPod(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['ExecInPod'](arg1, arg2, arg3, arg4, arg5);
}

export function FreeLocalPort() {
  return window['go']['wails']['ManagementAPI']['FreeLocalPort']();
}

export function ListPortForwards() {
  return window['go']['wails']['ManagementAPI']['ListPortForwards']();
}

export function ProbeLocalPort(arg1) {
  return window['go']['wails']['ManagementAPI']['ProbeLocalPort'](arg1);
}

export function RestartRollout(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['ManagementAPI']['RestartRollout'](arg1, arg2, arg3, arg4);
}

export function ScaleWorkload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['ScaleWorkload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['wails']['ManagementAPI']['StartPortForward'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function StopAllPortForwards() {
  return window['go']['wails']['ManagementAPI']['StopAllPortForwards']();
}

export function StopLogStream(arg1) {
  return window['go']['wails']['ManagementAPI']['StopLogStream'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['wails']['ManagementAPI']['StopPortForward'](arg1);
}

export function StreamLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['ManagementAPI']['StreamLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateResource(arg1, arg2) {
  return window['go']['wails']['ManagementAPI']['UpdateResource'](arg1, arg2);
}
