// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CordonNode(arg1, arg2, arg3) {
  return window['go']['wails']['ManagementAPI']['CordonNode'](arg1, arg2, arg3);
}

export function DeleteResource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['ManagementAPI']['DeleteResource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DrainNode(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['ManagementAPI']['DrainNode'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EvictPod(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['ManagementAPI']['EvictPod'](arg1, arg2, arg3, arg4);
}

export function ExecInPod(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['ExecInPod'](arg1, arg2, arg3, arg4, arg5);
}

export function ListPortForwards() {
  return window['go']['wails']['ManagementAPI']['ListPortForwards']();
}

export function PlanDrain(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['ManagementAPI']['PlanDrain'](arg1, arg2, arg3, arg4);
}

export function RestartRollout(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['ManagementAPI']['RestartRollout'](arg1, arg2, arg3, arg4);
}

export function ScaleWorkload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['ScaleWorkload'](arg1, arg2, arg3, arg4, arg5);
}

export function SetConfigMapKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['SetConfigMapKey'](arg1, arg2, arg3, arg4, arg5);
}

export function SetSecretKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['SetSecretKey'](arg1, arg2, arg3, arg4, arg5);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['wails']['ManagementAPI']['StartPortForward'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function StopLogStream(arg1) {
  return window['go']['wails']['ManagementAPI']['StopLogStream'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['wails']['ManagementAPI']['StopPortForward'](arg1);
}

export function StreamLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['ManagementAPI']['StreamLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SuspendWorkload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['wails']['ManagementAPI']['SuspendWorkload'](arg1, arg2, arg3, arg4, arg5);
}

export function TriggerCronJob(arg1, arg2, arg3) {
  return window['go']['wails']['ManagementAPI']['TriggerCronJob'](arg1, arg2, arg3);
}

export function UpdateResource(arg1, arg2) {
  return window['go']['wails']['ManagementAPI']['UpdateResource'](arg1, arg2);
}
