// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function Capability():Promise<wails.NotificationCapability>;

export function Notify(arg1:wails.NotificationRequest):Promise<void>;

export function Request():Promise<boolean>;
