// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Capability() {
  return window['go']['wails']['NotificationAPI']['Capability']();
}

export function Notify(arg1) {
  return window['go']['wails']['NotificationAPI']['Notify'](arg1);
}

export function Request() {
  return window['go']['wails']['NotificationAPI']['Request']();
}
