// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetOverview(arg1:string):Promise<wails.Overview>;

export function GetOverviewForTarget(arg1:string,arg2:string):Promise<wails.Overview>;
