// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CanI(arg1:string,arg2:wails.AccessRequest):Promise<wails.AccessDecision>;

export function InspectRole(arg1:string,arg2:string,arg3:string,arg4:string):Promise<wails.RoleInspection>;

export function SubjectRules(arg1:string,arg2:string):Promise<wails.SubjectRules>;
