// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanI(arg1, arg2) {
  return window['go']['wails']['RBACAPI']['CanI'](arg1, arg2);
}

export function InspectRole(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['RBACAPI']['InspectRole'](arg1, arg2, arg3, arg4);
}

export function SubjectRules(arg1, arg2) {
  return window['go']['wails']['RBACAPI']['SubjectRules'](arg1, arg2);
}
