// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Credits() {
  return window['go']['wails']['SystemAPI']['Credits']();
}

export function Info() {
  return window['go']['wails']['SystemAPI']['Info']();
}

export function LicenceText(arg1) {
  return window['go']['wails']['SystemAPI']['LicenceText'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['wails']['SystemAPI']['OpenURL'](arg1);
}
