// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseFile(arg1:string):Promise<string>;

export function Credits():Promise<Array<wails.Credit>>;

export function Info():Promise<wails.AppInfo>;

export function LicenceText(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;
