// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<string>;

export function StopSession(arg1:string):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
