// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Resize(arg1, arg2, arg3) {
  return window['go']['wails']['TerminalAPI']['Resize'](arg1, arg2, arg3);
}

export function StartAttachSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['TerminalAPI']['StartAttachSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartDebugSession(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['wails']['TerminalAPI']['StartDebugSession'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StartNodeShellSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['TerminalAPI']['StartNodeShellSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['TerminalAPI']['StartSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopSession(arg1) {
  return window['go']['wails']['TerminalAPI']['StopSession'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['wails']['TerminalAPI']['Write'](arg1, arg2);
}
