// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CheckForUpdate(arg1:boolean):Promise<wails.UpdateStatus>;

export function UpdateChecksPermitted():Promise<boolean>;
