// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPods(arg1) {
  return window['go']['wails']['WorkloadAPI']['ListPods'](arg1);
}
