// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPods(arg1, arg2) {
  return window['go']['wails']['WorkloadAPI']['ListPods'](arg1, arg2);
}

export function ListPodsForWorkload(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['WorkloadAPI']['ListPodsForWorkload'](arg1, arg2, arg3, arg4);
}

export function ListPodsOnNode(arg1, arg2) {
  return window['go']['wails']['WorkloadAPI']['ListPodsOnNode'](arg1, arg2);
}

export function ListWorkloads(arg1, arg2, arg3) {
  return window['go']['wails']['WorkloadAPI']['ListWorkloads'](arg1, arg2, arg3);
}

export function PodGraph(arg1, arg2, arg3) {
  return window['go']['wails']['WorkloadAPI']['PodGraph'](arg1, arg2, arg3);
}

export function WorkloadGraph(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['WorkloadAPI']['WorkloadGraph'](arg1, arg2, arg3, arg4);
}
