// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ListPods(arg1:string,arg2:string):Promise<Array<wails.Pod>>;

export function ListPodsForWorkload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<wails.Pod>>;

export function ListPodsOnNode(arg1:string,arg2:string):Promise<Array<wails.Pod>>;

export function ListWorkloads(arg1:string,arg2:string,arg3:string):Promise<Array<wails.Workload>>;

export function PodGraph(arg1:string,arg2:string,arg3:string):Promise<wails.PodGraph>;

export function WorkloadGraph(arg1:string,arg2:string,arg3:string,arg4:string):Promise<wails.PodGraph>;
