/**
 * The topology's calls into the backend, behind one seam.
 *
 * `TopologyAPI` is generated by `wails3 generate bindings` from
 * app/adapters/wails/topology_api.go: Topology(clusterID, namespaces, all),
 * Release(clusterID) and ExportTopologyPNG(suggestedName, pngBase64). The
 * generated types are WIDER than the contract — state and edge kinds are
 * plain strings, slices and maps may be null — so every graph is narrowed
 * once, in `normaliseGraph`, and nothing downstream guards a field.
 *
 * THE FIXTURE PATH is for tests and for working on the page without a
 * cluster: `useTopologyBackend(fixtureBackend(graph))` swaps the whole seam,
 * and in a dev build `?topology-fixture=<boxes>` in the URL does the same with
 * a generated graph. Nothing in a production build reads that parameter.
 *
 * Like `$lib/api/client`, this is the only place the page's backend calls go
 * through; the event subscription reuses the client's `subscribe`, which is
 * what keeps that module the only importer of the Wails runtime.
 */
import {
  ExportTopologyPNG as bindExportTopologyPNG,
  Release as bindRelease,
  Topology as bindTopology,
} from '$bindings/topologyapi'
import type * as wails from '$bindings/models'
import { subscribe } from '$lib/api/client'
import { ApiError, toApiError } from '$lib/api/errors'
import type {
  NodeState,
  TopologyChanged,
  TopologyEdge,
  TopologyEdgeKind,
  TopologyGraph,
  TopologyNode,
} from './contract'
import { fixtureTopology } from './fixtures'

/** The event the backend emits when something in a drawn scope changed. */
export const TOPOLOGY_CHANGED_EVENT = 'topology:changed'

/** Everything the page asks of the backend. */
export interface TopologyBackend {
  topology(clusterId: string, namespaces: string[], all: boolean): Promise<TopologyGraph>
  /** Saves a PNG through the native dialog; resolves to the path, or '' when cancelled. */
  exportTopologyPNG(suggestedName: string, pngBase64: string): Promise<string>
  onTopologyChanged(handler: (event: TopologyChanged) => void): () => void
  /** Stops `topology:changed` for a cluster whose topology page closed. */
  release(clusterId: string): Promise<void>
}

const STATES = new Set<NodeState>(['ok', 'warn', 'bad', 'neutral'])
const EDGE_KINDS = new Set<TopologyEdgeKind>([
  'owns',
  'selects',
  'routes',
  'scales',
  'protects',
  'policy-selects',
  'attaches',
  'runs-as',
])

/** Anything the graph is narrowed from: the generated type, the contract's, or nothing. */
type WideGraph = wails.TopologyGraph | TopologyGraph | null | undefined

/**
 * The generated graph, narrowed to the contract.
 *
 * A Go nil slice or map arrives as null; the page reads arrays and records.
 * A state the contract does not know is drawn neutral — "nothing checked" —
 * rather than as healthy, and an edge kind it does not know is dropped
 * rather than drawn as a relationship whose meaning nobody wrote down.
 */
export function normaliseGraph(graph: WideGraph): TopologyGraph {
  const nodes: TopologyNode[] = (graph?.nodes ?? []).map((node) => ({
    id: node.id,
    kind: node.kind,
    apiKind: node.apiKind,
    name: node.name,
    namespace: node.namespace,
    state: STATES.has(node.state as NodeState) ? (node.state as NodeState) : 'neutral',
    detail: node.detail ?? '',
    group: node.group ?? '',
    labels: (node.labels as Record<string, string> | null | undefined) ?? undefined,
    podSummary: node.podSummary
      ? {
          total: node.podSummary.total,
          ready: node.podSummary.ready,
          unhealthy: node.podSummary.unhealthy,
          members: node.podSummary.members ?? [],
        }
      : undefined,
  }))
  const edges: TopologyEdge[] = []
  for (const edge of graph?.edges ?? []) {
    if (!EDGE_KINDS.has(edge.kind as TopologyEdgeKind)) continue
    edges.push({ from: edge.from, to: edge.to, kind: edge.kind as TopologyEdgeKind, label: edge.label ?? '' })
  }
  return {
    nodes,
    edges,
    counts: (graph?.counts as Record<string, number> | null | undefined) ?? {},
    unreadable: graph?.unreadable ?? [],
    bounded: graph?.bounded ?? '',
    summarised: graph?.summarised ?? false,
    generatedAt: graph?.generatedAt ?? '',
  }
}

/** The real backend, through the generated bindings. */
export const bindingBackend: TopologyBackend = {
  async topology(clusterId, namespaces, all) {
    try {
      return normaliseGraph(await bindTopology(clusterId, namespaces, all))
    } catch (error) {
      throw error instanceof ApiError ? error : toApiError(error)
    }
  },
  async exportTopologyPNG(suggestedName, pngBase64) {
    try {
      return await bindExportTopologyPNG(suggestedName, pngBase64)
    } catch (error) {
      throw error instanceof ApiError ? error : toApiError(error)
    }
  },
  onTopologyChanged(handler) {
    return subscribe<TopologyChanged>(TOPOLOGY_CHANGED_EVENT, (payload) =>
      handler({ clusterId: payload?.clusterId ?? '', namespaces: payload?.namespaces ?? [] }),
    )
  },
  async release(clusterId) {
    try {
      await bindRelease(clusterId)
    } catch {
      // Optional by design: an unreleased scope expires on its own in Go, so a
      // failure here (a closing window, a lost backend) is not worth a word.
    }
  },
}

/**
 * A backend that answers from a graph in memory, for tests and for the dev
 * fixture. `emit` stands in for the backend's change event; `saved` records
 * what an export would have written.
 */
export interface FixtureBackend extends TopologyBackend {
  emit(event: TopologyChanged): void
  saved: { name: string; bytes: number }[]
  calls: { clusterId: string; namespaces: string[]; all: boolean }[]
  released: string[]
}

export function fixtureBackend(graph: TopologyGraph | (() => TopologyGraph)): FixtureBackend {
  const handlers = new Set<(event: TopologyChanged) => void>()
  const backend: FixtureBackend = {
    saved: [],
    calls: [],
    released: [],
    async topology(clusterId, namespaces, all) {
      backend.calls.push({ clusterId, namespaces: [...namespaces], all })
      const whole = typeof graph === 'function' ? graph() : graph
      if (all) return normaliseGraph(whole)
      const scope = new Set(namespaces)
      const nodes = whole.nodes.filter((node) => !node.namespace || scope.has(node.namespace))
      const kept = new Set(nodes.map((node) => node.id))
      // The whole graph's counts when nothing was scoped away — they may be
      // deliberately larger than what was sent, as a summarised graph's are.
      let counts = whole.counts
      if (nodes.length !== whole.nodes.length) {
        counts = {}
        for (const node of nodes) counts[node.apiKind] = (counts[node.apiKind] ?? 0) + 1
      }
      return normaliseGraph({
        ...whole,
        nodes,
        edges: whole.edges.filter((edge) => kept.has(edge.from) && kept.has(edge.to)),
        counts,
      })
    },
    async exportTopologyPNG(name, base64) {
      backend.saved.push({ name, bytes: Math.floor((base64.length * 3) / 4) })
      return `/tmp/${name}`
    },
    onTopologyChanged(handler) {
      handlers.add(handler)
      return () => handlers.delete(handler)
    },
    async release(clusterId) {
      backend.released.push(clusterId)
    },
    emit(event) {
      for (const handler of handlers) handler(event)
    },
  }
  return backend
}

let override: TopologyBackend | null = null

/** Replaces the backend — a test's fixture, or null to go back to the real one. */
export function useTopologyBackend(backend: TopologyBackend | null): void {
  override = backend
}

/** The dev-only fixture, from `?topology-fixture=<boxes>`; never in a production build. */
function devFixture(): TopologyBackend | null {
  if (!import.meta.env.DEV || typeof location === 'undefined') return null
  const size = Number(new URLSearchParams(location.search).get('topology-fixture'))
  if (!Number.isFinite(size) || size <= 0) return null
  override = fixtureBackend(fixtureTopology({ nodes: size, namespaces: Math.max(1, Math.round(size / 250)), unwellEvery: 17 }))
  return override
}

function backend(): TopologyBackend {
  return override ?? devFixture() ?? bindingBackend
}

/** TopologyAPI.Topology: the whole graph for a scope, folded in Go above the pod cap. */
export function topology(clusterId: string, namespaces: string[], all: boolean): Promise<TopologyGraph> {
  return backend().topology(clusterId, namespaces, all)
}

/** TopologyAPI.ExportTopologyPNG: the native save dialog for a rendered PNG. */
export function exportTopologyPNG(suggestedName: string, pngBase64: string): Promise<string> {
  return backend().exportTopologyPNG(suggestedName, pngBase64)
}

/** TopologyAPI.Release: stop the change feed for a cluster whose page closed. */
export function releaseTopology(clusterId: string): Promise<void> {
  return backend().release(clusterId)
}

/** `topology:changed`, as emitted by TopologyAPI's change feed. Returns an unsubscribe. */
export function onTopologyChanged(handler: (event: TopologyChanged) => void): () => void {
  return backend().onTopologyChanged(handler)
}

/**
 * Whether a change event concerns the drawn scope.
 *
 * An event naming no namespace is a cluster-scoped change — a CRD owner, a
 * Gateway's class — and is relevant to every scope, because there is no
 * namespace to rule it out by.
 */
export function changeConcerns(
  event: TopologyChanged,
  clusterId: string,
  scope: { namespaces: string[]; all: boolean },
): boolean {
  if (event.clusterId !== clusterId) return false
  if (scope.all || event.namespaces.length === 0) return true
  return event.namespaces.some((namespace) => scope.namespaces.includes(namespace))
}
