/**
 * The topology's calls into the backend, behind one seam.
 *
 * THE BINDINGS ARE FOUND, NOT IMPORTED. `TopologyAPI` is generated by
 * `wails3 generate bindings` from app/adapters/wails/topology_api.go into
 * `$bindings/topologyapi.ts`, and a static import of a file that a given
 * checkout has not generated yet would fail the build and the type check of
 * everything else. `import.meta.glob` resolves at build time to the file if
 * it exists and to nothing if it does not, so this module compiles either way
 * and starts calling the real backend the moment the bindings are generated —
 * nothing here changes when they are.
 *
 * Without them every call refuses with `TopologyUnavailableError`, an ApiError
 * that says what is missing and is not retryable, so the page shows a sentence
 * rather than a stack.
 *
 * THE FIXTURE PATH is for tests and for working on the page without a
 * cluster: `useTopologyBackend(fixtureBackend(graph))` swaps the whole seam,
 * and in a dev build `?topology-fixture=<boxes>` in the URL does the same with
 * a generated graph. Nothing in a production build reads that parameter.
 *
 * Like `$lib/api/client`, this is the only place the page's backend calls go
 * through; the event subscription reuses the client's `subscribe`, which is
 * what keeps that module the only importer of the Wails runtime.
 */
import { subscribe } from '$lib/api/client'
import { ApiError, toApiError } from '$lib/api/errors'
import type { TopologyChanged, TopologyGraph } from './contract'
import { fixtureTopology } from './fixtures'

/** The generated binding module's shape — the names the Go side is bound under. */
interface TopologyBindings {
  Topology(clusterID: string, namespaces: string[], all: boolean): Promise<TopologyGraph>
  ExportTopologyPNG(suggestedName: string, pngBase64: string): Promise<string>
}

/** The event the backend emits when something in a drawn scope changed. */
export const TOPOLOGY_CHANGED_EVENT = 'topology:changed'

/** Everything the page asks of the backend. */
export interface TopologyBackend {
  topology(clusterId: string, namespaces: string[], all: boolean): Promise<TopologyGraph>
  /** Saves a PNG through the native dialog; resolves to the path, or '' when cancelled. */
  exportTopologyPNG(suggestedName: string, pngBase64: string): Promise<string>
  onTopologyChanged(handler: (event: TopologyChanged) => void): () => void
}

/** A topology call made where no topology backend exists. */
export class TopologyUnavailableError extends ApiError {
  constructor() {
    super(
      'internal',
      'This build of PodSteer has no topology backend: its bindings were not generated. ' +
        'Run `make bindings` (or `wails3 generate bindings`) and rebuild.',
    )
    this.name = 'TopologyUnavailableError'
  }

  /** Pressing Retry cannot generate a file. */
  override get isRetryable(): boolean {
    return false
  }
}

// Relative rather than `$bindings`: the glob is resolved by Vite from this
// file, and a relative pattern is resolved identically by Vite and vitest.
const generated = import.meta.glob<TopologyBindings>(
  '../bindings/github.com/podsteer/podsteer/app/adapters/wails/topologyapi.ts',
)

async function bindings(): Promise<TopologyBindings> {
  const load = Object.values(generated)[0]
  if (!load) throw new TopologyUnavailableError()
  return load()
}

/**
 * A Go nil slice arrives as null, and a map as null; the page reads arrays and
 * records. Normalised once, here, so nothing downstream guards each field.
 */
export function normaliseGraph(graph: TopologyGraph | null | undefined): TopologyGraph {
  return {
    nodes: graph?.nodes ?? [],
    edges: graph?.edges ?? [],
    counts: graph?.counts ?? {},
    unreadable: graph?.unreadable ?? [],
    bounded: graph?.bounded ?? '',
    summarised: graph?.summarised ?? false,
    generatedAt: graph?.generatedAt ?? '',
  }
}

/** The real backend, through the generated bindings when they exist. */
export const bindingBackend: TopologyBackend = {
  async topology(clusterId, namespaces, all) {
    try {
      const api = await bindings()
      return normaliseGraph(await api.Topology(clusterId, namespaces, all))
    } catch (error) {
      throw error instanceof ApiError ? error : toApiError(error)
    }
  },
  async exportTopologyPNG(suggestedName, pngBase64) {
    try {
      const api = await bindings()
      return await api.ExportTopologyPNG(suggestedName, pngBase64)
    } catch (error) {
      throw error instanceof ApiError ? error : toApiError(error)
    }
  },
  onTopologyChanged(handler) {
    return subscribe<TopologyChanged>(TOPOLOGY_CHANGED_EVENT, (payload) =>
      handler({ clusterId: payload?.clusterId ?? '', namespaces: payload?.namespaces ?? [] }),
    )
  },
}

/**
 * A backend that answers from a graph in memory, for tests and for the dev
 * fixture. `emit` stands in for the backend's change event; `saved` records
 * what an export would have written.
 */
export interface FixtureBackend extends TopologyBackend {
  emit(event: TopologyChanged): void
  saved: { name: string; bytes: number }[]
  calls: { clusterId: string; namespaces: string[]; all: boolean }[]
}

export function fixtureBackend(graph: TopologyGraph | (() => TopologyGraph)): FixtureBackend {
  const handlers = new Set<(event: TopologyChanged) => void>()
  const backend: FixtureBackend = {
    saved: [],
    calls: [],
    async topology(clusterId, namespaces, all) {
      backend.calls.push({ clusterId, namespaces: [...namespaces], all })
      const whole = typeof graph === 'function' ? graph() : graph
      if (all) return normaliseGraph(whole)
      const scope = new Set(namespaces)
      const nodes = whole.nodes.filter((node) => !node.namespace || scope.has(node.namespace))
      const kept = new Set(nodes.map((node) => node.id))
      // The whole graph's counts when nothing was scoped away — they may be
      // deliberately larger than what was sent, as a summarised graph's are.
      let counts = whole.counts
      if (nodes.length !== whole.nodes.length) {
        counts = {}
        for (const node of nodes) counts[node.apiKind] = (counts[node.apiKind] ?? 0) + 1
      }
      return normaliseGraph({
        ...whole,
        nodes,
        edges: whole.edges.filter((edge) => kept.has(edge.from) && kept.has(edge.to)),
        counts,
      })
    },
    async exportTopologyPNG(name, base64) {
      backend.saved.push({ name, bytes: Math.floor((base64.length * 3) / 4) })
      return `/tmp/${name}`
    },
    onTopologyChanged(handler) {
      handlers.add(handler)
      return () => handlers.delete(handler)
    },
    emit(event) {
      for (const handler of handlers) handler(event)
    },
  }
  return backend
}

let override: TopologyBackend | null = null

/** Replaces the backend — a test's fixture, or null to go back to the real one. */
export function useTopologyBackend(backend: TopologyBackend | null): void {
  override = backend
}

/** The dev-only fixture, from `?topology-fixture=<boxes>`; never in a production build. */
function devFixture(): TopologyBackend | null {
  if (!import.meta.env.DEV || typeof location === 'undefined') return null
  const size = Number(new URLSearchParams(location.search).get('topology-fixture'))
  if (!Number.isFinite(size) || size <= 0) return null
  override = fixtureBackend(fixtureTopology({ nodes: size, namespaces: Math.max(1, Math.round(size / 250)), unwellEvery: 17 }))
  return override
}

function backend(): TopologyBackend {
  return override ?? devFixture() ?? bindingBackend
}

/** TopologyAPI.Topology: the whole graph for a scope, folded in Go above the pod cap. */
export function topology(clusterId: string, namespaces: string[], all: boolean): Promise<TopologyGraph> {
  return backend().topology(clusterId, namespaces, all)
}

/** TopologyAPI.ExportTopologyPNG: the native save dialog for a rendered PNG. */
export function exportTopologyPNG(suggestedName: string, pngBase64: string): Promise<string> {
  return backend().exportTopologyPNG(suggestedName, pngBase64)
}

/** `topology:changed`, as emitted by TopologyAPI's change feed. Returns an unsubscribe. */
export function onTopologyChanged(handler: (event: TopologyChanged) => void): () => void {
  return backend().onTopologyChanged(handler)
}

/**
 * Whether a change event concerns the drawn scope.
 *
 * An event naming no namespace is a cluster-scoped change — a CRD owner, a
 * Gateway's class — and is relevant to every scope, because there is no
 * namespace to rule it out by.
 */
export function changeConcerns(
  event: TopologyChanged,
  clusterId: string,
  scope: { namespaces: string[]; all: boolean },
): boolean {
  if (event.clusterId !== clusterId) return false
  if (scope.all || event.namespaces.length === 0) return true
  return event.namespaces.some((namespace) => scope.namespaces.includes(namespace))
}
