// Package assets embeds the compiled Svelte frontend into the binary.
//
// # Why the built frontend lives under app/
//
// Go's embed directive cannot reference a parent directory: patterns like
// `../../web/dist` are rejected by the compiler. Since all Go code lives under
// app/ and all frontend *source* lives under web/, the only way to embed the
// bundle is to have Vite emit it next to the package that embeds it — which is
// what web/vite.config.ts does with its `build.outDir`.
//
// The directory is build output, not source: it is generated by
// `npm run build`, recreated by `wails build`, and git-ignored.
package assets

import (
	"embed"
	"fmt"
	"io/fs"
)

// dist holds the compiled frontend.
//
// The `all:` prefix is required: without it the compiler silently skips files
// beginning with "_" or ".", which is exactly how Vite and SvelteKit name some
// of their output chunks. Losing one is a blank window at runtime.
//
//go:embed all:dist
var dist embed.FS

// FS returns the embedded frontend rooted at its index.html.
//
// Wails serves the returned filesystem from its root, so the "dist" prefix is
// stripped here rather than being left for the asset server to guess at.
//
// An error means the bundle is missing — the binary was compiled without the
// frontend having been built. That is a build mistake, and it is reported at
// startup rather than surfacing later as a blank window.
func FS() (fs.FS, error) {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		return nil, fmt.Errorf("embedded frontend is unavailable: %w", err)
	}

	if _, err := fs.Stat(sub, "index.html"); err != nil {
		return nil, fmt.Errorf(
			"embedded frontend is missing index.html: build it first with `npm --prefix web run build`: %w", err)
	}

	return sub, nil
}
